bcgov/nr-compliance-enforcement

backend/src/app.controller.spec.ts
backend/src/app.controller.ts

Removed the auth guard on the healthcheck endpoint.  Without this change, the healtcheck api will return a 401 error, and the lineness and readyness OpenShift probes will fail, which will result in the pods not starting up.
---
[Backend](https://nr-compliance-enforcement-19-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-19-frontend.apps.silver.devops.gov.bc.ca/) available
---
Any successful deployments (not …

Removed auth guard on health check endpoint

---

frontend/src/app/components/containers/complaints/details/complaint-header.tsx
frontend/src/app/components/modal/instances/assign-officer-modal.tsx
frontend/src/app/components/modal/modal.tsx

When opening the "Assign Officers" modal, the previous list of officers no longer flashes before being refreshed with the officers in the zone of the selected complaint.
The "Assign" button on the details pages will now be labelled as "Reassign" if there's already an officer assigned.
---
[Backend](https://nr-compliance-enforcement-71-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-71-frontend.apps.silver.devops.gov.bc.ca/) available

Compenf 608 refresh assignee list bug

---

frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx
frontend/src/app/store/reducers/complaints.ts
frontend/src/app/store/reducers/hwcr-complaints.ts
frontend/src/app/types/complaints/details/complaint-attactant.ts

Attractants are now populated on HWCR complaints.
Found a complaint with multiple attractants (23-000083), and verified that they are displayed on both the view and edit screen.
---
[Backend](https://nr-compliance-enforcement-90-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-90-frontend.apps.silver.devops.gov.bc.ca/) available

Attractants are now populated on edit screen

---

frontend/src/app/components/containers/complaints/complaint-details.tsx

When a new complaint is viewed after viewing a previous complaint, the previous complaint remains causing a flash of data when viewing a new complaint. This fix updates the complaint details to remove the complaint when the complaint-details component is unmounted.
Fixes # COMPENF-626
Existing tests will cover this

COMPENF-626 - Remove previous complaint

---

backend/src/external_api/bc_geo_coder/bc_geo_coder.controller.ts
backend/src/external_api/bc_geo_coder/bc_geo_coder.service.spec.ts
backend/src/external_api/bc_geo_coder/bc_geo_coder.service.ts
frontend/src/app/components/common/bc-geocoder-autocomplete.tsx
frontend/src/app/components/containers/complaints/details/complaint-location.tsx
frontend/src/app/store/reducers/complaints.ts

Made use of the localityName functionality of BC Geocoder.  This is a feature provided by BC Geocoder to use regional information instead of an address. If an address isn't provided, then just the community is used for the localityName.  If an address is provided, this is used in conjunction with the localityName (given by the community).
---
[Backend](https://nr-compliance-enforcement-115-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-115-frontend.apps.silver.devops.gov.bc.ca/) available
[Main Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement/actions/workflow …

COMPENF-648-Changed location parameters from param types to query types

---

backend/src/v1/attractant_hwcr_xref/attractant_hwcr_xref.service.ts
frontend/src/app/common/validation-input.tsx
frontend/src/app/components/common/bc-geocoder-autocomplete.tsx
frontend/src/app/components/containers/complaints/complaint-details.tsx
frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx
frontend/src/app/components/containers/complaints/details/complaint-location.tsx
frontend/src/app/components/mapping/leaflet-map-with-point.tsx
frontend/src/app/store/reducers/app.ts
frontend/src/app/store/reducers/complaints.ts
frontend/src/assets/sass/maps.scss

As an officer or Admin Staff, I want to be able to select the location of the complaint from a map while editing a complaint to ensure that the location information captured for that complaint is as accurate as possible.
---
[Backend](https://nr-compliance-enforcement-130-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-130-frontend.apps.silver.devops.gov.bc.ca/) available
[Main Merge …

Compenf-768-edit complaint location

---

frontend/src/app/common/api.ts
frontend/src/app/components/containers/complaints/complaint-filter.tsx
frontend/src/assets/sass/complaint.scss
frontend/src/assets/sass/layout.scss

---
[Backend](https://nr-compliance-enforcement-144-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-144-frontend.apps.silver.devops.gov.bc.ca/) available

Fix Filter Dropdowns not appearing properly

---

frontend/cypress/e2e/complaint-list.cy.ts
frontend/cypress/e2e/complaints-on-map-view.cy.ts
frontend/cypress/e2e/hwcr-details.cy.ts
frontend/src/app/components/containers/complaints/details/complaint-header.tsx
frontend/src/app/components/mapping/complaint-summary-popup.tsx
frontend/src/app/types/app/complaint-types.ts

Should not have Plural Human Wildlife Conflicts on Single Complaints
[COMPENF-996](https://apps.nrs.gov.bc.ca/int/jira/browse/COMPENF-996)
---
[Backend](https://nr-compliance-enforcement-151-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-151-frontend.apps.silver.devops.gov.bc.ca/) available
---
[Backend](https://nr-compliance-enforcement-151-backend.apps.silver.dev …

COMPENF-996-Should not have Plural Human Wildlife Conflicts on Single Complaints

---

frontend/cypress/e2e/change-complaint-assignee.cy.ts
frontend/cypress/e2e/change-complaint-status.cy.ts
frontend/cypress/support/commands.ts
frontend/src/app/components/containers/complaints/complaint-list.tsx
frontend/src/app/components/containers/complaints/complaints.tsx
frontend/src/app/providers/complaint-filter-provider.tsx
frontend/src/app/types/complaints/complaint-filters/complaint-filters.ts

Fixes the behaviour of the default zone filter. Initially the default zone is not being correctly applied, the update to the complaint filter provider applies the default zone as part of initial state opposed to setting the filter on load which has been causing the complaints list to be requested without the default zone being applied
Fixes # COMPENF-859
Existing tests handle this update
---
[Backend](https://nr-compliance-enforcement-154-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-154-frontend.apps.silver.devops.gov.bc.ca/) available
[Main Merge …

COMPENF-859: Default zone fix

---

frontend/cypress/e2e/allegation-details.cy.ts
frontend/src/app/components/common/non-dismissible-alert.tsx

Added a period to the end of the "The exact location of the complaint could not be determined" text.
---
[Backend](https://nr-compliance-enforcement-175-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-175-frontend.apps.silver.devops.gov.bc.ca/) available

CE-84-No-location-found-text-update

---

frontend/package-lock.json
frontend/src/app/components/containers/complaints/details/complaint-details-create.tsx
frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx

---
[Backend](https://nr-compliance-enforcement-178-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-178-frontend.apps.silver.devops.gov.bc.ca/) available

Preventing future dates

---

backend/src/external_api/bc_geo_coder/bc_geo_coder.service.ts
frontend/cypress/e2e/allegation-details.cy.ts
frontend/cypress/support/commands.ts
frontend/src/app/components/common/bc-geocoder-autocomplete.tsx
frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx
frontend/src/app/components/containers/complaints/details/complaint-location.tsx
frontend/src/app/components/mapping/leaflet-map-with-point.tsx
frontend/src/app/store/reducers/complaints.ts

A number of changes were made here to improve the edit complaint location and geocoding functionality.
1. Refactored variable names to improve readability
2. Reduced minScore from 2 to 1 on geocoding since the geocoder was being overly picky on locality names and addresses.
3. Complaint coordinates are now displayed on edit screen
4. Updates the lat/lng values when the coordinates change so that the map reflects the latest and greatest coordinates
Fixes # CE-199
---
[Backend](https://nr-compliance-enforcement-181-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-181-frontend.apps.silver.devops.gov.bc.ca/) available
Once merged, code will be promoted and …

CE-199-Refactoring of edit and geocoding functionality

---

frontend/cypress/e2e/complaint-filter-cascade.cy.ts
frontend/src/app/components/containers/complaints/complaint-filter.tsx
frontend/src/app/store/reducers/code-table.ts

Update the complaint filters to allow cascading of selected filters
Story #: CE-109
Cypress test the following:
---
[Backend](https://nr-compliance-enforcement-194-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-194-frontend.apps.silver.devops.gov.bc.ca/) available

feature/CE-109: Implement filter option cascading

---

frontend/src/app/store/reducers.ts
frontend/src/app/store/store.ts

This fix address a problem with how the redux state is persisted when the browser is closed, and previous state is reloaded. Prior to this fix the whole app state was persisted. This has been updated to exclude the app state, but to keep the alerts, profile, configuration and notification items. 
Fixes # CE-232
---
[Backend](https://nr-compliance-enforcement-197-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-197-frontend.apps.silver.devops.gov.bc.ca/) available

bug/CE-232 - fixed modal state persistance 

---

frontend/cypress/e2e/complaint-filter-cascade.cy.ts
frontend/src/app/store/reducers/code-table.ts

Update to how the community cascade functions. previously selecting a community would restrict the community filter to just the selected community. After the update the community dropdown will cascade to the zone showing only communities in the selected community zone.
Story # CE-109
existing test: Verifies regions and zones are cascaded when selecting a community updated to reflect change
---
[Backend](https://nr-compliance-enforcement-198-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-198-frontend.apps.silver.devops.gov.bc.ca/) available
[Main Merge …

feature/CE-109v2: community cascade update

---

backend/src/v1/complaint/complaint.controller.spec.ts
backend/src/v1/complaint/complaint.module.ts
backend/src/v1/complaint/complaint.service.spec.ts
backend/src/v1/complaint/complaint.service.ts

Set the agency ownership when creating a new complaint to the agency that is associated with the user creating the new complaint
Story # CE-216
A new service test has been created to verify that the complaint has a valid owned_by_agency_code agency code
~~- [ ] complaint.service - verify owned_by_agency_code has agency code of officer creating complaint~~
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~
~~- [ ] New and existing unit tests pass locally with my changes~~
unable to create unit tests at this point in time. unable to create mock objects to facilitate testing with typeORM's QueryRunner used during the create complaint process. Will need to revisit this drring continued refactoring of the complaint service
---
Any successful …

feature/CE-216 - Set complaint ownership on create

---

frontend/src/app/components/containers/complaints/complaint-ellipsis-popover.tsx
frontend/src/app/components/containers/complaints/details/complaint-details-create.tsx
frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx
frontend/src/app/components/containers/complaints/details/complaint-header.tsx
frontend/src/app/components/containers/complaints/list-items/complaint-action-items.tsx
frontend/src/app/components/modal/model-components.ts
frontend/src/app/store/reducers/complaints.ts
frontend/src/app/store/reducers/officer.ts
frontend/src/app/types/modal/modal-types.ts

When on the complaint list view when a user changes a complaint status, or changes the officer assignment the list view does not update with the new changes.
This fix addresses this and makes it so that when a user does change the status, or assigns a complaint to an officer that the list view is updated to reflect this change.
Fixes # CE-324
Existing cypress tests will cover this, no need for additional testing
---
[Backend](https://nr-compliance-enforcement-233-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-233-frontend.apps.silver.devops.gov.bc.ca/) available
[Main Merge …

Update complaint list view assignment and state changes

---

.github/workflows/merge-main.yml

WebEOC depends on NATS, so deploy NATS before the WebEOC container
Not tested in dev, needs to be tested on test migration.
---
[Backend](https://nr-compliance-enforcement-255-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-255-frontend.apps.silver.devops.gov.bc.ca/) available

bug: deploy nats before webeoc on test promotions

---

frontend/cypress/e2e/complaint-filter-cascade.cy.ts
frontend/src/app/store/reducers/code-table.ts

Updated the selector used to populate the community filter drop down. When no zone is selected, the community filter should not cascade
Fixes # CE-258
Existing tests should cover this fix
---
[Backend](https://nr-compliance-enforcement-265-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-265-frontend.apps.silver.devops.gov.bc.ca/) available

bug/CE-258 

---

frontend/cypress/e2e/hwcr-details-create-enter-coordinates.cy.ts
frontend/src/app/components/containers/complaints/details/complaint-details-create.tsx

When attempting to create a complaint with coordinates the application displays a toast “Unable to create complaint” and fails to save the complaint data.
The issue occurs because on the backend PostGIS fails to create geometry object from the input JSON if the object type is not passed.  To fix the issue I modified a front-end component to have the object type in addition to coordinates.
Fixes # (CE-447)
---
[Backend](https://nr-compliance-enforcement-276-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-276-frontend.apps.silver.devops.gov.bc.ca/) available
[Main Merge …

Fix saving complaints with coordinates - Bug/CE-447

---

backend/db/migrations/R__0.14.0__CE-101.sql
frontend/cypress/e2e/complaint-search.v2.cy.ts

Strip all non-numeric characters from the webEOC field
If the first digit is not a 1, prepend it.
If the first character is not a + prepend it to the field
---
[Backend](https://nr-compliance-enforcement-279-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-279-frontend.apps.silver.devops.gov.bc.ca/) available
[Main Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement/actions/workfl …

bug: Phone Numbers are not loaded from webEOC

---

frontend/src/app/components/containers/complaints/outcomes/animal-outcomes/add-animal-outcome.tsx

When adding an animal outcome to a complaint that has been assigned to an officer, the species list is not selected with the animal selected in the wildlife complaint.
Fixes # CE-487
---
[Backend](https://nr-compliance-enforcement-283-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-283-frontend.apps.silver.devops.gov.bc.ca/) available

bug/CE-487 - fixes problem with default values

---

frontend/src/app/components/containers/complaints/outcomes/animal-outcomes/add-animal-outcome.tsx
frontend/src/app/components/containers/complaints/outcomes/animal-outcomes/drug-authorization.tsx
frontend/src/app/components/containers/complaints/outcomes/animal-outcomes/edit-animal-outcome.tsx
frontend/src/app/components/containers/complaints/outcomes/hwcr-outcome-by-animal.tsx
frontend/src/app/store/reducers/complaints.ts

When adding a drug, if the user selects an officer and then reassigns the complaint, the selected officer in the drug authorization does not update to reflect the change in assigned officer
Fixes # CE-485
manually verified selected officer is updating when complaint is reassigned
---
[Backend](https://nr-compliance-enforcement-282-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-282-frontend.apps.silver.devops.gov.bc.ca/) available

bug/CE-485 - updated authorized drug assignment behaviour

---

frontend/src/app/components/containers/complaints/outcomes/animal-outcomes/add-drug.tsx
frontend/src/app/components/containers/complaints/outcomes/animal-outcomes/animal-outcome-item.tsx
frontend/src/app/components/containers/complaints/outcomes/animal-outcomes/drug-item.tsx

Updated the animal outcome and drug item components to handle optional fields. When selecting drug fate other than discarded, the discarded fields are not displayed, and when selected are displayed
Fixes # CE-486
---
[Backend](https://nr-compliance-enforcement-285-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-285-frontend.apps.silver.devops.gov.bc.ca/) available

bug/CE-486 - update drug item fields

---

frontend/src/app/components/modal/instances/assign-officer-modal.tsx
frontend/src/assets/sass/modals.scss

When searching for an officer to assign to a complaint, if the user had previously selected an officer, the previously selected officers index remains selected, incorrectly selecting a new officer
Fixes # CE-533
---
[Backend](https://nr-compliance-enforcement-300-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-300-frontend.apps.silver.devops.gov.bc.ca/) available

bug/CE-533 - update selected officer when assigning officer to complaint

---

frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx

When editing a complaint, when the user saves their changes the browser does not scroll to top. Added fix to scroll user to top of page on save edit
story # CE-531
---
[Backend](https://nr-compliance-enforcement-306-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-306-frontend.apps.silver.devops.gov.bc.ca/) available
[Main Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement/actions/workflows/merg …

feature/CE-531: scroll to top when editing

---

frontend/src/app/common/validation-checkbox-group.tsx
frontend/src/app/components/containers/complaints/outcomes/hwcr-complaint-assessment.tsx
frontend/src/app/store/reducers/cases.ts

This is to fix the issue when Save Assessment does not display saved info after user navigate away & back
Fixes # CE-560
---
[Backend](https://nr-compliance-enforcement-318-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-318-frontend.apps.silver.devops.gov.bc.ca/) available

bug/CE-560 Save Assessment sometimes does not display saved info

---

frontend/src/app/components/containers/complaints/outcomes/hwcr-complaint-assessment.tsx
frontend/src/app/components/containers/complaints/outcomes/hwcr-prevention-education.tsx
frontend/src/app/types/outcomes/assessment.ts
frontend/src/app/types/outcomes/prevention.ts

Fixes a problem in the validation of both the assessment and prevention and education where if a user doesn't select an option from the checkbox list will cause the validation to fail.
Fixes # CE-595
This addresses errors when tested against the CE-410 case-management branch
---
[Backend](https://nr-compliance-enforcement-331-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-331-frontend.apps.silver.devops.gov.bc.ca/) available

fix: save assessment/prevention functionality

---

frontend/src/app/components/containers/complaints/outcomes/hwcr-complaint-assessment.tsx
frontend/src/app/components/containers/complaints/outcomes/hwcr-prevention-education.tsx
frontend/src/app/store/reducers/case-thunks.ts

This PR address the issue of Save Assessment sometimes displays officer GUID instead of name
Fixes # (CE-553)
---
[Backend](https://nr-compliance-enforcement-359-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-359-frontend.apps.silver.devops.gov.bc.ca/) available

fix: CE-553 - Ensure officer list is populated

---

frontend/src/app/components/containers/complaints/outcomes/hwcr-complaint-assessment.tsx
frontend/src/app/components/containers/complaints/outcomes/hwcr-prevention-education.tsx
frontend/src/app/store/reducers/case-thunks.ts
frontend/src/app/store/store.ts

The cause of the issue described in CE-553 is when a user refreshes the complaint details the data (officer list) that is supposed to be in Redux state is missing. It only occurs in the test environment. Debugging found the the app attempts to run setOfficers action but it happens late in a sequence when complaint detail component is already rendered.  
The code is modified to retrieve the Redux state in the Assessment and Prevention and Eductions sections in the same way as it was done in other sections. Also the list of officers is added to a dependency array of useEffect that refresh the view. It should re-render Complaint Details component when officer list is populated.
Fixes # (CE-553)
Please describe the tests that you ran to verify your changes. Provide instructions so we can …

bug: CE-553 Resolve the issue of GUID in the officer field

---

backend/db/migrations/R__0.14.0__CE-101.sql

Fixes # CE-744
---
[Backend](https://nr-compliance-enforcement-444-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-444-frontend.apps.silver.devops.gov.bc.ca/) available

Remove data truncation from Call Details field

---

frontend/src/app/components/containers/complaints/list-items/complaint-action-items.tsx
frontend/src/app/store/reducers/case-thunks.ts

This PR is to fix an issue when Status Modal for Pending Review complaint briefly displays dropdown before displaying validation message
Fixes # (CE-766)
---
[Backend](https://nr-compliance-enforcement-450-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-450-frontend.apps.silver.devops.gov.bc.ca/) available
[Main Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement/actions/workflows/merge-mai …

bug: CE-766-Status-Modal-for-Pending-Review-complaint-briefly-displays-dropdown-before-displaying-validation-message

---

frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/create-outcome.tsx
frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/edit-outcome.tsx

Fixes CE-800
Note: This PR also fixes an unreported bug that after an outcome edit, validation messages aren't visible.
---
[Backend](https://nr-compliance-enforcement-472-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-472-frontend.apps.silver.devops.gov.bc.ca/) available
[Main Merge …

fix: CE-800 Do not default officer/date on outcome

---

frontend/src/app/components/containers/complaints/outcomes/hwcr-complaint-assessment.tsx
frontend/src/app/components/modal/instances/change-status-modal.tsx

This PR is allow users to close a complaint when Action required is Yes and the Prevention and education section is not completed
Fixes # (CE-835)
---
[Backend](https://nr-compliance-enforcement-485-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-485-frontend.apps.silver.devops.gov.bc.ca/) available

feat:CE-835-Remove-rule-for-closing-a-complaint

---

backend/src/middleware/maps/automapper-entity-to-dto-maps.ts
backend/src/v1/complaint/complaint.service.ts

Update to the export complaint to prevent the export process from failing and returning an empty complaint 
Fixes # CE-848
---
[Backend](https://nr-compliance-enforcement-493-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-493-frontend.apps.silver.devops.gov.bc.ca/) available

fix: bug/CE-848: Complaints Created in NatComplaints without an Incident Date/Time can't be exported

---

backend/src/v1/complaint/complaint.service.ts
frontend/src/app/components/containers/complaints/complaint-list.tsx
frontend/src/app/components/containers/complaints/headers/wildlife-complaint-list-header.tsx

updated the search query to correctly use the area_name opposed to the area_code when sorting by community
When sorting by community in the list view the search was incorrectly using the wrong column to sort on. Code updated to use the community name rather than the community code.
Fixes # CE-746
Manually tested to confirm correct sort order. To confirm: 
- load list view, HWCR or ERS
- sort by community
- skip to the communities starting with C
- verify correct sorting, communities should not go from Cluculz Lake back to Campbell River 
---
[Backend](https://nr-compliance-enforcement-499-frontend.apps.silver.devops.gov.bc.ca/api/) available …

fix: CE-746 - complaint list view community sorting incorrect

---

frontend/src/app/common/validation-date-picker.tsx
frontend/src/app/components/containers/complaints/complaint-filter.tsx
frontend/src/app/components/containers/complaints/details/complaint-details-create.tsx
frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx
frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/drug-used.tsx

The date pickers currently only show a single month, this should instead show two months and restrict the selectable date to the max date of today. The date pickers have been updated to all display the previous and current month when selecting a new date, and restrict all delectable dates to a max date of the current date.
Fixes # CE-752
- Manually testes
---
[Backend](https://nr-compliance-enforcement-504-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-504-frontend.apps.silver.devops.gov.bc.ca/) available
[Main Merge …

fix: CE-752 - Date filter default months

---

frontend/src/app/components/containers/complaints/webeoc-complaint-updates/webeoc-complaint-update-list.tsx

The complaint update banners incorrectly had the latitude and longitude values displayed. This update corrects and swaps the two values and labels
Fixes # CE-870
- manually tested
---
[Backend](https://nr-compliance-enforcement-507-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-507-frontend.apps.silver.devops.gov.bc.ca/) available

fix: updated location update labels

---

frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/drug-used.tsx

When editing or creating an animal outcome with a drug, the amount used and amount discarded will allow a user to add an animal outcome with values of 0. This has been updated to prevent this from happening and only allowing users to use positive values.
Fixes # CE-729
- existing tests
- manually tested
---
[Backend](https://nr-compliance-enforcement-506-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-506-frontend.apps.silver.devops.gov.bc.ca/) available

fix: bug/CE-729 - updated animal outcome validation

---

frontend/cypress.config.ts

Fixes # CE-893
---
[Backend](https://nr-compliance-enforcement-515-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-515-frontend.apps.silver.devops.gov.bc.ca/) available

chore: Retry Cypress tests twice after failure

---

.github/workflows/merge-hotfix.yml
.github/workflows/merge-main.yml

When merging to main, promote to production.
---
- [Frontend](https://nr-compliance-enforcement-552-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-552-frontend.apps.silver.devops.gov.bc.ca/api)

feat: CE-906 merge main updates

---

frontend/src/app/components/containers/complaints/details/complaint-details-create.tsx
frontend/src/app/store/reducers/code-table.ts

Creates a new dropdown listing which is limited to those types that are createable which is in turn used to populate the options in the Create page.
---
- [Frontend](https://nr-compliance-enforcement-561-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-561-frontend.apps.silver.devops.gov.bc.ca/api)
- …

fix: Creates new filter for Creatable Types - filters out GIR.

---

frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/animal-outcome.tsx

Fixed an issue where the animal title information would show bullet separators when no sex and/or age was defined.
---
- [Frontend](https://nr-compliance-enforcement-577-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-577-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …

fix: CE-984 - Bullet Separators Show Up With Empty Spaces When No Values Entered for Sex and/or Age

---

frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/drug-item.tsx

Updated/fixed the label in the read-only view of the animal form for 'Drugs administered by' so it's consistent with the edit/form view.
---
- [Frontend](https://nr-compliance-enforcement-576-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-576-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …

fix: CE-985 - Fix Inconsistent Label in Animal Outcome Read-only View

---

frontend/src/app/components/containers/complaints/complaints.tsx

The default CEEB filters would fail when users switched complaint tabs.  For example, prior to this change, the default filters would work when a user accesses the application; however, as soon as the user switched tabs, the defaults were wrong.
Fixes # (CE-941
---
- [Frontend](https://nr-compliance-enforcement-594-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-594-frontend.apps.silver.devops.gov.bc.ca/api)
- [Analysis …

feat: CE-941 attempt3

---

frontend/src/app/components/containers/complaints/complaint-list-tabs.tsx

This PR is to fix an issue when a tab label for "Waste and Pesticides" incorrectly displayed as "Enforcement"
Fixes # (CE-1009)
---
- [Frontend](https://nr-compliance-enforcement-595-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-595-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …

fix: CE-1009-enforcement-tex-on-tab-instead-of-waste-and-pesticides-in-ceeb-officer-view

---

migrations/migrations/V0.25.1__CE-892.sql
migrations/migrations/V0.26.2__CE-1017.sql

Changes now are done by using a new versioned script rather than making modifications to the earlier script that created the table.
Identified as part of the deploy process.
---
- [Frontend](https://nr-compliance-enforcement-627-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-627-frontend.apps.silver.devops.gov.bc.ca/api)
- …

fix: Modifies how the contstraint is added to the feature_agency_xref

---

backend/src/v1/case_file/case_file.controller.ts
backend/src/v1/case_file/case_file.service.ts
frontend/src/app/components/containers/complaints/outcomes/ceeb/ceeb-decision/decision-form.tsx
frontend/src/app/components/containers/complaints/outcomes/ceeb/ceeb-decision/decision-item.tsx
frontend/src/app/components/containers/complaints/outcomes/ceeb/ceeb-decision/decision.tsx
frontend/src/app/store/reducers/case-selectors.ts
frontend/src/app/store/reducers/case-thunks.ts
frontend/src/app/types/app/case-files/case-file.ts

Unable to save Decision section without entering all fields - incorrect toast
Fixes # CE-1059
---
- [Frontend](https://nr-compliance-enforcement-629-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-629-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement/act …

fix: CE-1059 Unable to save Decision section without entering all fields - incorrect toast

---

frontend/src/app/components/containers/complaints/complaint-filter-bar.tsx

Fixes CE=750
Updates Date Filter pill to display the current date when only one date is selected instead of a range.
---
- [Frontend](https://nr-compliance-enforcement-697-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-697-frontend.apps.silver.devops.gov.bc.ca/api)
- [Analysis Workflow](https://github.com/bcgov/nr-compliance-enforcement/actio …

feat: CE-750 Display Current Date in Filter when only one date selected

---

migrations/migrations/R__reset-templates.sql

Fixes # CE-1075
Added a flyway script that is guaranteed to run during every push in order to always push new templates to CDOGS
---
- [Frontend](https://nr-compliance-enforcement-700-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-700-frontend.apps.silver.devops.gov.bc.ca/api)
- [Analysis …

fix: Clear CDOGS templates with every run

---

.github/workflows/pr-version-bump.yml
.github/workflows/release-branch-creation.yml

Changes the way the appropriate git tag is selected. Instead of using `git describe --tags` to select the tag, which is only returning the first tag it uses `git tag --merged` which should select all tags that have been merged into the current branch. It's not clear exactly why `git describe` isn't working, but it has different logic to select the best or closest tag based on the branch history, not necessarily the newest tag. 
References:
[https://git-scm.com/docs/git-describe](https://git-scm.com/docs/git-describe)
[https://stackoverflow.com/questions/67190989/when-and-why-exactly-does-git-describe-not-show-the-latest-tag](https://stackoverflow.com/questions/67190989/when-and-why-exactly-does-git-describe-not-show-the-latest-tag)
Question:
- How are branches merged into main?
TBD
--- …

fix: CE 1124

---

frontend/src/app/components/containers/complaints/outcomes/ceeb/authorization-outcome/authorization-outcome.tsx
frontend/src/app/components/modal/instances/assign-officer-modal.tsx
frontend/src/assets/sass/layout.scss

This PR is to apply a scroll bar to the Assign modal
Fixes # (CE-1143)
CE-1142
---
- [Frontend](https://nr-compliance-enforcement-710-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-710-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement/actions/workflows/ …

fix: CE-1143-apply-scroll-bar-to-assign-modal

---

.github/workflows/merge-main.yml
.github/workflows/merge-release.yml
charts/app/values.yaml
migrations/migrations/R__reset-templates.sql

enable autoscaling for test and bump NATS replicas
Fixes # (CE-917)
---
- [Frontend](https://nr-compliance-enforcement-702-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-702-frontend.apps.silver.devops.gov.bc.ca/api)

fix: CE-917 enable autoscaling for test

---

frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/create-outcome.tsx
frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/edit-outcome.tsx

Addresses [CE-909](https://env-ceds.atlassian.net/browse/CE-909). Addresses issue where data entered into one animal outcome drug field would swap around to other drugs. 
- Drug items now use an ordering function to ensure consistent order, and therefore entries. 
1. Run a local instance of the application, log in and create a new issue. 
2. Under _'Outcome by Animal'_, click _'Add animal'_.
3. In animal outcome form, click 'Add drug' multiple times.
4. In the first record, enter information in the fields. Information entered should stay in that record. Information entered into other records should stay in their respective record.
[CE-1120]: https://env-ceds.atlassian.net/browse/CE-1120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Addresses …

fix: CE-909 Animal outcome drug forms reorder unexpectedly

---

frontend/src/app/App.tsx
frontend/src/app/components/containers/pages/index.ts
frontend/src/app/components/containers/pages/not-authorized.tsx
frontend/src/app/components/containers/pages/not-found.tsx
frontend/src/app/components/error-handling/generic-error-boundary.tsx
frontend/src/assets/sass/errors.scss

Fixes # CE-1080
Adds a link to the home page of the application on the 3 error pages (Not Found, Not Authorized, Generic Error)
Also includes a standization of wording and tidy of the CSS to make the messaging display consistently on all screen sizes.
---
- [Frontend](https://nr-compliance-enforcement-719-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-719-frontend.apps.silver.devops.gov.bc.ca/api) …

feat: Add link to home page from error pages

---

frontend/src/app/components/containers/complaints/complaint-list.tsx
frontend/src/app/components/mapping/leaflet-map-with-multiple-points.tsx

Addresses [CE-749](https://env-ceds.atlassian.net/browse/CE-749). Adds information to adjust filters when no complaints return. 
- Add message to filtered list display.
- Change message in map display. 
1. Run a local instance of the application, log in. 
2. On the complaints list page, add filters until no items return.
- A message should display in the list view: _"No complaints found using your current filters. Remove or change your filters to see complaints."_.
3. On the complaints map page, add filters until no items return.
- A message should display in the alert box: _"No complaints found using your current filters. Remove or change your filters to see complaints."_.
[CE-749]: https://env-ceds.atlassian.net/browse/CE-749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …

chore: CE-749 Display message to user to remove filters when no complaints are found

---

frontend/src/app/components/common/comp-coordinate-input.tsx

This PR is to fix the error message text when entering UTM coordinates.
Fixes # (CE-1175)
---
- [Frontend](https://nr-compliance-enforcement-728-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-728-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement/actions …

fix: CE-1175-correct-error-message-text

---

backend/src/v1/complaint/complaint.service.ts

Complaints service's `mapSearch` function uses the local function `_getAgencyByUser` to determine a users agency. This function identifies a users agency through the office they are assigned to. CEEB users have no office assigned, thus `_getAgencyByUser` fails. To get around this, `mapSearch` now uses the `hasCEEBRole` variable already included to determine if `_getAgencyByUser` should be called, or "EPO" should be assigned (as is the case for CEEB users). Current implementation of tests do not address the problem, and there was an existing false positive in the tests for the complaints service. This will be addressed separately.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details …

chore: Fix mapSearch agency check for CEEB users

---

.github/scripts/cleanup_scan.sh

Adds a script that can be used to find dangling resources in a given namespace. After we've done a few rounds of cleaning it'd be good to place this into CICD as a scheduled check.
NOTE: I'm running cleanup after demos are all done, here's a sample run of what it's finding:
```
jon-funk@Atlas:~/projects/nr-compliance-enforcement/.github/scripts$ ALLOW_EXPR="object-store" SKIP_AUTH=true ./cleanup_scan.sh 
ALLOW_EXPR: object-store
Scanning for workloads older than 30 days in the targeted namespace
...
Found 15 workloads older than 30 days in the targeted namespace
Scanning for dangling secrets not used by workloads
... …
```

chore: add cleanup scan script for finding dangling / old resources

---

frontend/src/app/components/containers/complaints/complaint-filter.tsx
frontend/src/app/providers/complaint-filter-provider.tsx
frontend/src/app/store/reducers/complaints.ts

Fixed persistence bugs in the search when returning to the complaints page.
Fixed the date filters to get parsed into state in the complaint filters provider. This prevents the app from entering a broken state when loading a fresh complaint filter context with stored start or end date filters in the search params.
Fixed the map search function to now set the complaint search parameters in state. This fixes the bug of filters set in map not setting the complaint search parameters.
Fixes:
https://env-ceds.atlassian.net/jira/software/c/projects/CE/boards/4?selectedIssue=CE-1276
https://env-ceds.atlassian.net/jira/software/c/projects/CE/boards/4?selectedIssue=CE-1277
Tested by following the steps to reproduce in the bug cards and ensuring that the site remained in a functional state.
--- …

fix: CE-1276 1277 stored filter fixes

---

frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/edit-outcome.tsx
frontend/src/app/components/modal/instances/standalone-cancel-confirm-modal.tsx

This PR is to address an issue when users edit outcome details after public reports have been published by showing a warning message.
Fixes # (CE-1261)
Click the Edit button and select new outcome or outcome date. Check if the warning message is displayed. Click No on the modal, check if the changes your have made are rolled back. 
Select new outcome or outcome date again. When the modal is displayed click Yes, check if your changes are preserved. 
---
Deployments, as required, will be …

feat: CE-1261-add-warning-message-to-user-attempting-to-edit-the-outcome-or-outcome-date-in-a-hwc-file-v2

---

.github/workflows/release-main.yml

This shouldn't be needed but it appears githhub is not respecting the code of the pulled deployer action. As v0.8.3 has the correct curl command. https://github.com/bcgov/nr-compliance-enforcement/actions/runs/12224172977/job/34096599350
https://github.com/bcgov/quickstart-openshift-helpers/blob/main/.github/workflows/.deployer.yml#L125
---
- [Frontend](https://nr-compliance-enforcement-806-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-806-frontend.apps.silver.devops.gov.bc.ca/api)
Please create PRs in draft mode. …

fix: switch to bearer token val

---

frontend/src/app/common/validation-phone-input.tsx
frontend/src/app/components/containers/complaints/outcomes/hwcr-file-review.tsx
frontend/src/app/components/modal/instances/assign-officer-modal.tsx

Remove red warnings in browser console in development mode
---
- [Frontend](https://nr-compliance-enforcement-811-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-811-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement/actions/workflows/merg …

chore: CE-1103 cleanup warnings in frontend

---

backend/src/v1/complaint/complaint.service.ts
backend/src/v1/officer/officer.service.ts
frontend/src/app/components/containers/complaints/complaint-filter.tsx
frontend/src/app/components/containers/complaints/complaint-map-with-server-side-clustering.tsx
frontend/src/app/components/mapping/complaint-summary-popup.tsx

---
- [Frontend](https://nr-compliance-enforcement-817-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-817-frontend.apps.silver.devops.gov.bc.ca/api)

fix: Map Search Filters / Officers

---

frontend/src/app/components/containers/complaints/complaint-map-with-server-side-clustering.tsx

Fixes https://env-ceds.atlassian.net/jira/software/c/projects/CE/boards/4/backlog?selectedIssue=CE-1314
---
- [Frontend](https://nr-compliance-enforcement-823-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-823-frontend.apps.silver.devops.gov.bc.ca/api)

fix: Fix map sort params

---

frontend/src/app/common/validation-checkbox-group.tsx
frontend/src/app/common/validation-phone-input.tsx
frontend/src/app/components/common/attachments-carousel.tsx
frontend/src/app/components/common/comp-coordinate-input.tsx
frontend/src/app/components/common/complaint-pagination.tsx
frontend/src/app/components/containers/admin/feature-management.tsx
frontend/src/app/components/containers/complaints/list-items/allegation-complaint-list-item.tsx
frontend/src/app/components/containers/complaints/list-items/wildlife-complaint-list-item.tsx
frontend/src/app/components/containers/complaints/outcomes/ceeb/ceeb-decision/decision-item.tsx
frontend/src/app/components/containers/complaints/outcomes/hwcr-complaint-assessment.tsx
frontend/src/app/components/containers/complaints/outcomes/hwcr-equipment/equipment-form.tsx
frontend/src/app/components/containers/complaints/outcomes/hwcr-outcome-by-animal-v2.tsx
frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/animal-outcome.tsx
frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/drug-authorized-by.tsx
frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/drug-item.tsx
frontend/src/app/components/containers/complaints/outcomes/outcome-attachments.tsx
frontend/src/app/components/containers/zone-at-a-glance/office-user-container.tsx
frontend/src/app/components/modal/instances/assign-officer-modal.tsx
frontend/src/app/components/modal/instances/cancel-confirm-modal.tsx
frontend/src/app/components/modal/instances/delete-confirm-modal-v2.tsx
frontend/src/app/components/modal/instances/standalone-cancel-confirm-modal.tsx
frontend/src/app/store/reducers/app.ts

Fixes Frontend warnings, except SCSS deprecation warnings that are in bootstrap itself.
---
- [Frontend](https://nr-compliance-enforcement-827-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-827-frontend.apps.silver.devops.gov.bc.ca/api)

chore: CE-1274

---

backend/src/v1/complaint/complaint.service.ts

This PR is to order attachments in the PDF export by a file type
Fixes # (CE-1330)
---
- [Frontend](https://nr-compliance-enforcement-838-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-838-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement/actions/workfl …

fix: CE-1330-Attachment-Sort-Order-on-Export

---

charts/app/templates/backend/templates/deployment.yaml
charts/app/templates/frontend/templates/deployment.yaml
charts/app/templates/webeoc/templates/deployment.yaml
charts/app/values.yaml
database/openshift.deploy.yml
webeoc/src/publishers/actions-taken-publisher.service.ts
webeoc/src/publishers/complaints-publisher.service.ts
webeoc/src/subscribers/actions-taken-subscriber.service.ts
webeoc/src/subscribers/complaints-subscriber.service.ts

Dear OpenShift Project Teams,
We’re excited to share that as of this morning, December 10, 2024, we’ve made updates to the Quota section to enhance its flexibility and usability:
Removal of Resource Limits - The concept of limit has been removed. OpenShift now uses only request values configured by the OpenShift Provisioner.
What this means: Resource requests configured for a namespace are always guaranteed, while additional resources are only available when node capacity allows.
Why limits were removed: Setting CPU limits on Kubernetes can lead to inefficiencies and CPU throttling, even when additional resources are available. By relying on requests, we ensure that resources are reserved for critical workloads without unnecessary constraints, enabling optimal resource utilization and …

chore: remove limits (cpu and memory)

---

frontend/src/app/components/containers/complaints/outcomes/ceeb/authorization-outcome/authorization-outcome-form.tsx

This PR is to address CEEB  IPM  team request to update validation in the authorization number field. Now it accepts up to 20 characters including ‘-' and '/’ 
Fixes # (CE-1306)
---
- [Frontend](https://nr-compliance-enforcement-840-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-840-frontend.apps.silver.devops.gov.bc.ca/api)
- [Analysis …

fix: CE-1306-Update-validation-for-CEEB-Authorization-number-field-to-accept-Pesticide-related-authorizations

---

performance_tests/Makefile
performance_tests/README.md
performance_tests/backend_script.js
performance_tests/common/auth.js
performance_tests/common/params.js
performance_tests/frontend_script.js
performance_tests/tests/backend/complaint_details.js
performance_tests/tests/backend/mapSearch.js
performance_tests/tests/backend/search.js
performance_tests/tests/frontend/browser.js
performance_tests/tests/frontend/protocol.js

Added load testing code and configuration to the repository.
This PR introduces code to perform load tests on the application. More details, including instructions, can be found in `performance_tests/README.md`. K6 tooling was used to write the tests, which include back- and front-end protocol level tests as well as browser level tests for the front-end which simulates a user logging in and using the app. A sibling PR was created to add more test data prior to running the tests.
Platform Services are to be notified before running tests beyond the smoke test level load. 
---
Deployments, …

feat: Ce 1222 load tests

---

backend/src/v1/case_file/case_file.service.ts

---
- [Frontend](https://nr-compliance-enforcement-858-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-858-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …

fix: CE-1339 Linking to child complaint

---

frontend/src/app/constants/ceeb-roles.ts

Added the new roles Inspector and Province-wide to the list of roles used by the edit users page.
Verified that both Inspector and Province-wide are available in the dropdown menu when editing a users roles.
---
- [Frontend](https://nr-compliance-enforcement-859-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-859-frontend.apps.silver.devops.gov.bc.ca/api)

chore: CE-1354 Add new roles to list in edit user

---

frontend/src/app/components/common/comp-select.tsx
frontend/src/app/components/containers/complaints/details/complaint-details-create.tsx
frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx
frontend/src/app/store/reducers/code-table.ts
frontend/src/app/types/app/option.ts
migrations/migrations/V0.35.3__CE-1360.sql

https://env-ceds.atlassian.net/browse/CE-1360
Hides inactive HWCR Nature of Complaint options by adding an optional behaviour to the comp-select component.
---
- [Frontend](https://nr-compliance-enforcement-889-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-889-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …

fix: CE-1360 Hide inactive HWCR Nature of Complaint options

---

frontend/cypress/e2e/complaint-export.cy.ts
frontend/src/app/components/containers/complaints/details/complaint-header.tsx
webeoc/src/webeoc-scheduler/webeoc-scheduler.service.ts

Changes WebEOC logic to import based on created date not logged date.
https://env-ceds.atlassian.net/browse/CE-1383
---
- [Frontend](https://nr-compliance-enforcement-904-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-904-frontend.apps.silver.devops.gov.bc.ca/api)

fix: CE-1383 Change WebEOC Jan 1 Behavior

---

frontend/cypress/e2e/general_incident-details.cy.ts
frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx
frontend/src/app/components/containers/complaints/outcomes/gir-outcome-report.tsx
frontend/src/app/components/containers/complaints/outcomes/supplemental-notes/supplemental-notes-item.tsx
frontend/src/app/components/modal/instances/delete-note-modal.tsx

Add additional notes section to GIR
GIR complaints have been given an outcome report allowing users to add additional notes. Doing so will  open a case in CM.
Fixes # 1138
https://env-ceds.atlassian.net/jira/software/c/projects/CE/boards/4?selectedIssue=CE-1138
Sibling branch in CM: https://github.com/bcgov/nr-compliance-enforcement-cm/pull/119
---
- [Frontend](https://nr-compliance-enforcement-897-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-897-frontend.apps.silver.devops.gov.bc.ca/api)
Please create PRs in …

feat: Add GIR outcome report with additional notes

---

frontend/src/app/components/common/comp-coordinate-input.tsx
frontend/src/app/components/containers/complaints/details/complaint-details-create.tsx
frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx
frontend/src/app/components/containers/complaints/outcomes/hwcr-complaint-assessment.tsx
frontend/src/app/components/containers/complaints/outcomes/hwcr-equipment/equipment-form.tsx
frontend/src/app/components/containers/complaints/outcomes/hwcr-prevention-education.tsx
frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/drug-authorized-by.tsx
frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/drug-used.tsx
frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/ear-tag.tsx
frontend/src/app/components/containers/complaints/outcomes/supplemental-notes/supplemental-notes-input.tsx
frontend/src/assets/sass/complaint.scss
frontend/src/assets/sass/form.scss

- Any field that is required for the outcome report section to saved is marked with an Asterisk
- There are two cases where special handling was required:
- On the quick close modal 'Action Required?' does not have an indicator as it is forced to be 'No'
- On the equipment section either Location/address or Coordinates are required so a title has been added and the labels are indented.   On smaller screens where the labels/inputs stack the inputs are also indented.
Fixes # CE-1270
--- …

feat: Mandatory Field Indicators for Outcome Report Sections

---

backend/src/app.module.ts
backend/src/v1/agency_code/entities/agency_code.entity.ts
backend/src/v1/case_file/case_file.service.spec.ts
backend/src/v1/code-table/code-table.controller.spec.ts
backend/src/v1/code-table/code-table.module.ts
backend/src/v1/code-table/code-table.service.spec.ts
backend/src/v1/code-table/code-table.service.ts
backend/src/v1/complaint/complaint.service.spec.ts
backend/src/v1/complaint/complaint.service.ts
backend/src/v1/document/document.controller.spec.ts
backend/src/v1/document/document.service.spec.ts
backend/src/v1/violation_agency_xref/entities/violation_agency_entity_xref.ts
backend/src/v1/violation_agency_xref/violation_agency_xref.module.ts
backend/src/v1/violation_code/entities/violation_code.entity.ts
backend/test/mocks/mock-code-table-repositories.ts
frontend/src/app/components/containers/complaints/details/complaint-details-create.tsx
migrations/migrations/R__0.24.0_ceeb_violation_types.sql
migrations/migrations/R__Create-Test-Data.sql
migrations/migrations/V0.37.1__CE-1380.sql

- Provide support for Parks users to be able to create a complaint
- Refactor violation_code and agency_code relationship to be a many-to-many as Parks and COS may share complaint types
Fixes # (issue) CE-1380
---
- [Frontend](https://nr-compliance-enforcement-939-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-939-frontend.apps.silver.devops.gov.bc.ca/api)
Please create PRs in draft mode.  Mark as …

feat: Enable creating complaints for Parks users

---

frontend/src/app/components/common/comp-coordinate-input.tsx
frontend/src/app/components/common/comp-select.tsx
frontend/src/app/components/containers/admin/user-management/edit-user.tsx
frontend/src/app/components/containers/admin/user-management/select-user.tsx
frontend/src/app/components/containers/complaints/complaint-filter.tsx
frontend/src/app/components/containers/complaints/details/complaint-details-create.tsx
frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx
frontend/src/app/components/containers/complaints/outcomes/ceeb/ceeb-decision/decision-form.tsx
frontend/src/app/components/containers/complaints/outcomes/hwcr-complaint-assessment.tsx
frontend/src/app/components/containers/complaints/outcomes/hwcr-equipment/equipment-form.tsx
frontend/src/app/components/containers/complaints/outcomes/hwcr-file-review.tsx
frontend/src/app/components/containers/complaints/outcomes/hwcr-prevention-education.tsx
frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/create-outcome.tsx
frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/drug-authorized-by.tsx
frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/drug-used.tsx
frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/ear-tag.tsx
frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/edit-outcome.tsx
frontend/src/app/components/containers/complaints/outcomes/supplemental-notes/supplemental-notes-input.tsx
frontend/src/app/store/reducers/code-table.ts

Refactor Comp Select making showInactive required.
The `showInactive` prop on CompSelect is now required. For options that don't have the `isActive` field, all options will be shown. The PR has no change on the current frontend behaviour.
Fixes # 1400
https://env-ceds.atlassian.net/jira/software/c/projects/CE/boards/4?selectedIssue=CE-1400
---
- [Frontend](https://nr-compliance-enforcement-935-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-935-frontend.apps.silver.devops.gov.bc.ca/api)
Please create PRs in draft …

chore: CE-1400

---

.github/workflows/pr-version-bump.yml
.github/workflows/release-branch-creation.yml
.github/workflows/release-main.yml
backend/package.json
frontend/package.json
webeoc/package.json

Fix the automated tagging and versioning in the pipeline.
This PR implements the following changes:
- Versioning will be switched to a three digit semantic versioning pattern x.y.z
- Upon creation of a release branch, the current version will be taken from the package.json in the frontend (all 3 are being kept in sync, there's nothing special about the frontend), and have the minor (`y`) version bumped using `npm version minor`
- The version is set to this new version in the frontend, backend and webeoc package.json files, and a new git tag is created on the release branch
- When branches are merged into the release branch, the same process is applied only using a patch (`z`) level bump rather than a minor. The new tag is pointed at the merge commit of the feature branch into the release …

chore: CE-1476 fix tagging and versioning

---

.github/scripts/rollout_healthcheck.sh

Refetching the workloads and pods after the polling has finished.
By refetching the lists before passing them to the triage function, this should give the deployment time to finish and only get the list of relevant pods and workloads.
Fixes # CE-1310
---
- [Frontend](https://nr-compliance-enforcement-962-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-962-frontend.apps.silver.devops.gov.bc.ca/api)
- [Analysis …

chore: Refeetch workload and pod list after polling

---

.github/workflows/pr-version-bump.yml

Use the GitHub app to commit in the action.
A BCGov wide GitHub app was made for our repo(s). We can use it to make commits in our actions / workflows. The app needs to be added to the bypass list for branch protection rules in order to commit directly to `release/` branches.
---
- [Frontend](https://nr-compliance-enforcement-972-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-972-frontend.apps.silver.devops.gov.bc.ca/api)
- [Analysis …

chore: Use github app to commit to release branch

---

.github/workflows/pr-version-bump.yml
.github/workflows/release-branch-creation.yml
frontend/src/app/components/common/attachment-upload.tsx

Temporarily disable the commit to release in workflow.
The commit directly to the release branch is causing the get latest PR number action to return null for the latest PR. This breaks the merge-release workflow. This temporarily removes the commit from the workflow to unblock the pipeline while the proper workaround is found.
---
- [Frontend](https://nr-compliance-enforcement-981-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-981-frontend.apps.silver.devops.gov.bc.ca/api)
Please create PRs in …

chore: Temporarily disable commit in workflow

---

migrations/migrations/R__update_log_complaint_update.sql

Fixes # CE-1548
---
- [Frontend](https://nr-compliance-enforcement-987-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-987-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …

fix: use previous value instead of null on webeoc edit

---

backend/package.json
charts/app/Chart.yaml
frontend/package-lock.json
frontend/package.json
frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx
frontend/src/app/components/containers/complaints/details/complaint-location.tsx
frontend/src/app/components/mapping/leaflet-map-with-point.tsx
frontend/src/app/types/maps/map-element.ts
frontend/src/assets/sass/maps.scss
webeoc/package.json

This PR is to let COS officers view the location of the equipment on the complaint details map so that they can easily see where the equipment is located.
Fixes # (CE-1551)
---
- [Frontend](https://nr-compliance-enforcement-1023-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1023-frontend.apps.silver.devops.gov.bc.ca/api)
After merge, new images are …

feat: CE-1551-View-equipment-on-the-map-on-the-complaint-details

---

backend/package.json
charts/app/Chart.yaml
frontend/package.json
frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx
frontend/src/app/components/mapping/leaflet-map-with-point.tsx
webeoc/package.json

This PR is to fix two issues. One is when equipment pin appears on map for complaints without equipment after viewing a complaint with equipment. Another one is when K9 Unit and Less Lethal equipment appear as Active on the map.
Fixes # (CE-1606, CE-1607)
---
- [Frontend](https://nr-compliance-enforcement-1025-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1025-frontend.apps.silver.devops.gov.bc.ca/api)
- [Analysis …

fix: CE-1606-and-CE-1607

---

.gitignore
backend/package.json
charts/app/Chart.yaml
frontend/cypress/e2e/complaint-collaborators.cy.ts
frontend/package.json
frontend/src/app/components/containers/complaints/outcomes/notes.tsx
frontend/src/app/components/containers/complaints/outcomes/notes/note-item.tsx
webeoc/package.json

Allow collaborators to add notes
Users need the ability to add notes to complaints that they have been added as a collaborator on. This PR adds a check to the Notes component to check if the user is a collaborator, and prevents disabling of the functionality if they are.
Fixes # 1556
https://env-ceds.atlassian.net/jira/software/c/projects/CE/boards/4?selectedIssue=CE-1556
---
- [Frontend](https://nr-compliance-enforcement-1032-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1032-frontend.apps.silver.devops.gov.bc.ca/ …

feat: CE-1556 Allow collaborators to add notes

---

backend/package-lock.json
backend/package.json
charts/app/Chart.yaml
frontend/package.json
frontend/src/app/components/containers/admin/user-management/edit-user.tsx
webeoc/package.json

The issue here is that when a user changes a CEEB officer, the refreshed roles aren't pulled into Redux so it looks like the change did not take place unless the app is refreshed.   The fix was to pull the refreshed officer list after the change had been made.
Fixes # CE-1639
---
- [Frontend](https://nr-compliance-enforcement-1057-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1057-frontend.apps.silv …

fix: Refresh officer list when user admin updates user

---

backend/package.json
backend/src/external_api/shared_data.ts
backend/src/v1/shared_data/case_file/case_file.service.ts
charts/app/Chart.yaml
frontend/package.json
frontend/src/app/components/containers/complaints/outcomes/hwcr-assessment/hwcr-assessment-form.tsx
frontend/src/app/components/containers/complaints/outcomes/hwcr-assessment/hwcr-assessment-item.tsx
frontend/src/app/components/containers/complaints/outcomes/notes/note-form.tsx
frontend/src/app/components/containers/complaints/outcomes/notes/note-item.tsx
frontend/src/app/components/containers/complaints/outcomes/notes/note.tsx
frontend/src/app/store/reducers/case-thunks.ts
frontend/src/app/types/outcomes/note.ts
webeoc/package.json

This PR is to allow editing notes, assessment and prevention/education only by the agency which added them.
Fixes # (CE-1624)
---
- [Frontend](https://nr-compliance-enforcement-1093-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1093-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …

feat: CE-1624 Lead agency of a complaint cannot edit data provided by other agency

---

backend/package.json
charts/app/Chart.yaml
frontend/package.json
frontend/src/app/components/containers/complaints/outcomes/notes/note-item.tsx
webeoc/package.json

This PR is to fix a bug when a collaborator is unable to edit notes of the complaint they were invited to collaborate to.
Fixes # (CE-1693)
---
- [Frontend](https://nr-compliance-enforcement-1094-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1094-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …

fix: CE-1693 collab can no longer add notes to a complaint

---

backend/package.json
charts/app/Chart.yaml
frontend/package.json
frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx
webeoc/package.json

This PR is to fix an issue when officer GUIDS are displayed instead of names in the outcome assessment and prevention/education sections when direct linking to a complaint
Fixes # (CE-1709)
In an incognito window access the complaint directly. Check if officer names are displayed in a view mode of the assessment and prevention/education sections.
---
- [Frontend](https://nr-compliance-enforcement-1119-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1119-frontend.apps.silver.devops.gov.bc.ca/api)
Please create PRs in …

fix: CE-1709 Officers GUIDS not translated in some sections when direct linking to a complaint

---

backend/package.json
backend/src/v1/complaint_referral/complaint_referral.service.ts
charts/app/Chart.yaml
frontend/package.json
frontend/src/app/components/containers/complaints/complaint-list.tsx
frontend/src/app/components/containers/complaints/list-items/sector-complaint-list-item.tsx
webeoc/package.json

- Refer a complaint to an external agency, then verify the sector list does not error.
---
- [Frontend](https://nr-compliance-enforcement-1147-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1147-frontend.apps.silver.devops.gov.bc.ca/api)

fix: Sector View - Use code table instead of type for agency description

---

backend/package.json
charts/app/Chart.yaml
frontend/package.json
frontend/src/app/components/modal/instances/refer-complaint-modal.tsx
webeoc/package.json

This PR is to ensure that the modal footer that contains Refer and  Cancel buttons is not hidden on the devices with small screen size.
Fixes # (CE-1765)
---
- [Frontend](https://nr-compliance-enforcement-1170-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1170-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …

fix: CE-1765-refer-button-hidden-in-modal-on-smaller-screen-sizes-not-i-pad

---

backend/package.json
charts/app/Chart.yaml
frontend/package.json
frontend/src/assets/sass/misc.scss
webeoc/package.json

Make disabled datepicker on ipad legible.
The disabled datepicker on the ipad was getting a reduced opacity making it illegible. This forces it's opacity to 100%.
Fixes # CE-839
Tested on an iPad simulator via XCode on a mac.
---
- [Frontend](https://nr-compliance-enforcement-1173-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1173-frontend.apps.silver.devops.gov.bc.ca/api)

chore: CE-839 fix disabled datepicker colors on ipad

---

backend/package.json
charts/app/Chart.yaml
frontend/package-lock.json
frontend/package.json
frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx
frontend/src/app/components/containers/complaints/details/complaint-header.tsx
frontend/src/app/components/containers/complaints/details/linked-complaint-list.tsx
frontend/src/app/components/containers/complaints/list-items/complaint-action-items.tsx
frontend/src/app/components/containers/complaints/outcomes/hwcr-assessment/hwcr-assessment-form.tsx
frontend/src/app/components/modal/instances/link-complaint-modal.tsx
webeoc/package.json

- Allows linking actions on closed complaints
- Fixes search component not searching on copy/paste if a complaint has already been selected
- Fixes linked complaints not being fetched for complaint types other than HWCR
- Fixes warning not showing when linking to a complaint that is already linked
---
- [Frontend](https://nr-compliance-enforcement-1223-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1223-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …

fix: CE-1719 Tweaks

---

backend/package.json
charts/app/Chart.yaml
frontend/package.json
frontend/src/app/components/modal/instances/link-complaint-modal.tsx
webeoc/package.json

Update banner logic for linking complaints modal.
Duplicate complaints were being included in the linked complaints banner. This addresses the checks the populate the banner.
Fixes # [(issue)](https://env-ceds.atlassian.net/browse/CE-1912)
---
- [Frontend](https://f208ae-dev-7-natsuite-frontend.apps.emerald.devops.gov.bc.ca)
- [Merge …

feat: CE-1912 Update link complaints banner logic
