bcgov/nr-compliance-enforcement

frontend/src/assets/sass/layout.scss
Fixes # COMPENF-360
---
[Backend](https://nr-compliance-enforcement-43-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-43-frontend.apps.silver.devops.gov.bc.ca/) available
=> fixed collapsed sidebar icon size

frontend/src/assets/sass/layout.scss
Fixes # COMPENF-362
---
[Backend](https://nr-compliance-enforcement-44-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-44-frontend.apps.silver.devops.gov.bc.ca/) available
=> BUG-COMPENF-362: fixed weird animation when opening and closing sidebar

.github/workflows/pr-open.yml, frontend/openshift.deploy.yml
Correctly set KEYCLOAK_URL on pull request deployments so that each environment (dev/test/prod) has its own keycloak URL.
---
[Backend](https://nr-compliance-enforcement-49-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-49-frontend.apps.silver.devops.gov.bc.ca/) available
=> Keycloak environment variable

frontend/src/app/App.tsx, frontend/src/assets/sass/layout.scss
---
[Backend](https://nr-compliance-enforcement-57-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-57-frontend.apps.silver.devops.gov.bc.ca/) available
[Main Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement/actions/w …
=> Updates to Layout to fix header and sidebar

frontend/src/app/components/containers/complaints/complaint-container.tsx
=> Fixing sort order for non-date columns

.github/pull_request_template.md, .github/workflows/pr-open.yml, frontend/cypress.config.ts, frontend/cypress/e2e/spec.cy.ts, frontend/cypress/support/commands.ts, frontend/src/__test__/App.test.tsx
Fixed a cypress issue in the local environment, but also verified that it works in the pipeline.
Tested both locally and in the pipeline
---
[Backend](https://nr-compliance-enforcement-59-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-59-frontend.apps.silver.devops.gov.bc.ca/) available
--- …
=> COMPENF-394 - Jest/Unit Test Errors

backend/src/v1/allegation_complaint/allegation_complaint.service.ts, backend/src/v1/hwcr_complaint/hwcr_complaint.service.ts, frontend/src/app/components/containers/complaints/allegations/allegation-complaint-tab-container.tsx, frontend/src/app/components/containers/complaints/allegations/allegation-complaint-table.tsx, frontend/src/app/components/containers/complaints/complaint-container.tsx, frontend/src/app/components/containers/complaints/hwcr/hwcr-complaint-tab-container.tsx, frontend/src/app/components/containers/complaints/hwcr/hwcr-complaint-table.tsx, frontend/src/app/types/complaints/allegation-complaint.ts, frontend/src/app/types/complaints/hwcr-complaint.ts, frontend/src/assets/sass/complaint.scss, frontend/yarn.lock
---
[Backend](https://nr-compliance-enforcement-62-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-62-frontend.apps.silver.devops.gov.bc.ca/) available
=> Compenf 386, compenf 318, update timestamp adjustment, minor refactors

backend/src/v1/office/dto/create-office.dto.ts, backend/src/v1/office/office.controller.spec.ts, backend/src/v1/office/office.controller.ts, backend/src/v1/office/office.service.spec.ts, backend/src/v1/office/office.service.ts, backend/src/v1/officer/dto/create-officer.dto.ts, backend/src/v1/officer/officer.controller.spec.ts, backend/src/v1/officer/officer.module.ts, backend/src/v1/officer/officer.service.spec.ts, backend/src/v1/officer/officer.service.ts, backend/src/v1/person/dto/create-person.dto.ts, backend/src/v1/person/person.controller.spec.ts, backend/src/v1/person/person.service.spec.ts, backend/src/v1/person/person.service.ts
---
[Backend](https://nr-compliance-enforcement-60-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-60-frontend.apps.silver.devops.gov.bc.ca/) available
[Main Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement/actions/w …
=> Compenf-320-person-officer-office-apis

bcgovpubcode.yml
Fixes # (issue) COMPENF-629 - Add BC Gov Code File to Repo
---
[Backend](https://nr-compliance-enforcement-77-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-77-frontend.apps.silver.devops.gov.bc.ca/) available
[Main Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement/actions/wor …
=> Public-code-initial

.github/workflows/merge-main.yml, .github/workflows/pr-open.yml, frontend/cypress/e2e/allegation-details.cy.ts, frontend/cypress/e2e/hwcr-details.cy.ts
Update github action to use github environment variables to set the keycloak auth url
---
[Backend](https://nr-compliance-enforcement-76-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-76-frontend.apps.silver.devops.gov.bc.ca/) available
---
[Backend](https://nr-compliance-enforcement-76-backend.apps.silver.devops.gov.bc.ca/) available …
=> COMPENF-383

frontend/src/app/components/containers/complaints/allegations/allegation-complaint-filter-container.tsx, frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx, frontend/src/app/components/containers/complaints/hwcr/hwcr-complaint-filter-container.tsx, frontend/src/assets/sass/complaint.scss, frontend/src/assets/sass/misc.scss
- [ X ] New and existing unit tests pass locally with my changes
---
[Backend](https://nr-compliance-enforcement-87-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-87-frontend.apps.silver.devops.gov.bc.ca/) available
[Main Merge …
=> COMPENF-650 COMPENF-680 CSS Updates for Calendar Icon and Consistency

frontend/src/app/components/codes/complaint-status-select.tsx, frontend/src/app/components/containers/complaints/allegations/allegation-complaint-filter-container.tsx, frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx, frontend/src/app/components/containers/complaints/hwcr/hwcr-complaint-filter-container.tsx, frontend/src/assets/sass/complaint.scss, frontend/src/assets/sass/misc.scss
Fixes # COMPENF-680, plus a minor refactor to update styles names ceds to comp
---
[Backend](https://nr-compliance-enforcement-88-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-88-frontend.apps.silver.devops.gov.bc.ca/) available
[Main Merge …
=> COMPENF-680 update select css on modal

frontend/src/app/App.tsx, frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx, frontend/src/app/components/modal/instances/assign-officer-modal.tsx, frontend/src/app/store/reducers/complaints.ts, frontend/src/app/store/reducers/officer.ts, frontend/src/app/store/store.ts, frontend/src/app/types/complaints/officers-in-zone-state.ts, frontend/src/app/types/complaints/officers-state.ts, frontend/src/app/types/person/person.ts
Moved to selectors for retrieving officers by zone.
---
[Backend](https://nr-compliance-enforcement-97-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-97-frontend.apps.silver.devops.gov.bc.ca/) available
[Main Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement/ac …
=> officer refactor

frontend/cypress/e2e/allegation-details-edit.cy.ts, frontend/cypress/e2e/hwcr-details-edit.cy.ts, frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx
Changed "Widness" to "Witness"
Changed "Area/Community" to just "Community"
---
[Backend](https://nr-compliance-enforcement-98-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-98-frontend.apps.silver.devops.gov.bc.ca/) available
=> COMPENF-698-Fixed typos

frontend/src/app/components/containers/layout/side-bar.tsx, frontend/src/assets/sass/layout.scss, frontend/src/assets/sass/misc.scss
---
[Backend](https://nr-compliance-enforcement-99-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-99-frontend.apps.silver.devops.gov.bc.ca/) available
---
Thanks for the …
=> add tooltips to collapsed sb, fix collapse links

frontend/src/app/components/containers/zone-at-a-glance/office-user-container.tsx
---
[Backend](https://nr-compliance-enforcement-102-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-102-frontend.apps.silver.devops.gov.bc.ca/) available
=> Fixing warning

frontend/src/app/common/api.ts, frontend/src/app/components/codes/complaint-status-select.tsx, frontend/src/app/components/containers/complaints/allegations/allegation-complaint-filter-container.tsx, frontend/src/app/components/containers/complaints/hwcr/hwcr-complaint-filter-container.tsx, frontend/src/app/service/user-service.tsx, frontend/src/app/store/reducers/app.ts, frontend/src/app/store/reducers/code-table.ts, frontend/src/app/store/reducers/complaints.ts, frontend/src/app/store/reducers/office.ts, frontend/src/app/store/reducers/officer.ts, frontend/src/app/types/api-params/complaint-query-params.ts, frontend/src/app/types/api-params/complaint-update-params.ts, frontend/src/app/types/api-params/new-person-complaint-xref.ts, frontend/src/app/types/app/api-request-parameters.ts, frontend/src/app/types/app/app-state.ts, frontend/src/app/types/state/notification-state.ts
Task # COMPENF-391
Existing tests will cover changes made in this pull request, no additional tests needed
---
[Backend](https://nr-compliance-enforcement-101-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-101-frontend.apps.silver.devops.gov.bc.ca/) available
--- …
=> COMPENF-391-API

frontend/src/app/common/api.ts, frontend/src/app/components/containers/complaints/allegations/allegation-complaint-table.tsx, frontend/src/app/components/containers/complaints/complaint-container.tsx, frontend/src/app/components/containers/complaints/hwcr/hwcr-complaint-table.tsx
updated complaints list component to clear complaints when switching tabs to prevent data flashing
Update to the complaints tab component to clear complaints when switching between complaint types
Fixes: COMPENF-727
Existing test will cover these changes, no changes to underlying functionality.
---
[Backend](https://nr-compliance-enforcement-108-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-108-frontend.apps.silver.devops.gov.bc.ca/) available
=> COMPENF-727

frontend/cypress.config.ts, frontend/cypress/e2e/allegation-details-edit.cy.ts, frontend/cypress/e2e/allegation-details.cy.ts, frontend/cypress/e2e/change-complaint-assignee-details-view.cy.ts, frontend/cypress/e2e/change-complaint-assignee.cy.ts, frontend/cypress/e2e/change-complaint-filters-view.cy.ts, frontend/cypress/e2e/change-complaint-status-details-view.cy.ts, frontend/cypress/e2e/change-complaint-status.cy.ts, frontend/cypress/e2e/hwcr-details-edit.cy.ts, frontend/cypress/e2e/hwcr-details.cy.ts, frontend/cypress/e2e/spinner.spec.cy.ts, frontend/cypress/e2e/zone-at-a-glance-header.cy.ts, frontend/cypress/e2e/zone-at-a-glance-office.cy.ts, frontend/cypress/e2e/zone-at-a-glance-setup.cy.ts, frontend/cypress/support/commands.ts
---
[Backend](https://nr-compliance-enforcement-105-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-105-frontend.apps.silver.devops.gov.bc.ca/) available
=> COMPENF-695 Refactor Cypress Tests to Remove Waits

frontend/src/app/components/containers/zone-at-a-glance/zone-at-a-glance.tsx, frontend/src/assets/sass/colours.scss, frontend/src/assets/sass/complaint.scss, frontend/src/assets/sass/layout.scss, frontend/src/assets/sass/misc.scss, frontend/src/assets/sass/variables.scss, frontend/src/assets/sass/zone-at-a-glance.scss
Replaced hard-coded colours with colour variables.
---
[Backend](https://nr-compliance-enforcement-107-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-107-frontend.apps.silver.devops.gov.bc.ca/) available
---
[Backend](https://nr-compliance-enforcement-107-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-107-frontend.apps.silver.devops.g …
=> Compenf-655-392

backend/src/enum/person_complaint_xref_code.enum.ts, backend/src/v1/person/entities/person.entity.ts, backend/src/v1/person_complaint_xref/person_complaint_xref.controller.ts, backend/src/v1/person_complaint_xref/person_complaint_xref.service.ts, frontend/src/app/common/api.ts, frontend/src/app/store/reducers/officer.ts
Assign officer request is now atomic.  
On the frontend, only a single API call is made to assign an officer to a complaint.
On the backend, a new assign officer endpoint has been created (person-complaint-xref).  This will unassign an officer (if assigned), and assign the new officer to the complaint.  This is done in a transaction in case any of the intermediary procedures fail (in which case the entire transaction is rolled back).
---
[Backend](https://nr-compliance-enforcement-110-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-110-frontend.apps.silver.devops.gov.bc.ca/) available
Once merged, code will be promoted and handed off to following …
=> Compenf-697-Officer API refactor

frontend/src/app/components/mapping/leaflet-map-with-point.tsx, frontend/src/assets/sass/maps.scss
Added a border radius to the map
---
[Backend](https://nr-compliance-enforcement-113-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-113-frontend.apps.silver.devops.gov.bc.ca/) available
=> Added border-radius to map

backend/src/v1/hwcr_complaint/hwcr_complaint.service.ts, frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx, frontend/src/app/types/complaints/hwcr-complaint.ts, frontend/src/app/types/personComplaintXref.ts
---
[Backend](https://nr-compliance-enforcement-120-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-120-frontend.apps.silver.devops.gov.bc.ca/) available
=> Compenf 453 3

backend/src/v1/allegation_complaint/allegation_complaint.service.ts, backend/src/v1/attractant_hwcr_xref/attractant_hwcr_xref.service.ts, backend/src/v1/complaint/complaint.service.ts, backend/src/v1/person_complaint_xref/person_complaint_xref.service.ts, frontend/src/app/components/containers/complaints/complaint-details.tsx, frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx, frontend/src/app/store/reducers/code-table.ts, frontend/src/app/types/complaints/allegation-complaint.ts
---
[Backend](https://nr-compliance-enforcement-129-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-129-frontend.apps.silver.devops.gov.bc.ca/) available
=> COMPENF-459, COMPENF-841, COMPENF-864, COMPENF-860

frontend/src/app/components/containers/complaints/complaint-details.tsx, frontend/src/app/components/mapping/leaflet-map-with-point.tsx
Complaint location on map was not displayed when viewing the details screen.
---
[Backend](https://nr-compliance-enforcement-131-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-131-frontend.apps.silver.devops.gov.bc.ca/) available
=> COMPENF-865

backend/db/migrations/R__WebEOC-July-ERS-complaints.sql
---
[Backend](https://nr-compliance-enforcement-133-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-133-frontend.apps.silver.devops.gov.bc.ca/) available
=> Update geometry for test data

backend/package.json, backend/src/v1/allegation_complaint/allegation_complaint.service.spec.ts, backend/src/v1/person/person.controller.spec.ts, backend/src/v1/person/person.service.spec.ts, backend/src/v1/violation_code/violation_code.controller.spec.ts, backend/src/v1/violation_code/violation_code.service.spec.ts, backend/test/mocks/authGuardMock.ts, backend/test/mocks/datasource.ts, backend/test/mocks/mockType.ts, backend/test/mocks/personRepositoryMockFactory.ts, backend/test/mocks/roleGuardMock.ts, backend/test/mocks/violationCodeRepositoryMockFactory.ts
---
[Backend](https://nr-compliance-enforcement-136-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-136-frontend.apps.silver.devops.gov.bc.ca/) available
=> Jest-updates

frontend/src/app/components/containers/complaints/complaint-details.tsx, frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx
Fixed problem where removing coordinates was not removing coordinates properly, skipping over update logic
Fixes # COMPENF-878
---
[Backend](https://nr-compliance-enforcement-142-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-142-frontend.apps.silver.devops.gov.bc.ca/) available
=> fixed incorrect handling of removing coordinates

frontend/cypress/e2e/change-complaint-assignee.cy.ts, frontend/cypress/e2e/change-complaint-status.cy.ts, frontend/src/app/components/containers/complaints/complaints.tsx, frontend/src/assets/sass/layout.scss
---
[Backend](https://nr-compliance-enforcement-141-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-141-frontend.apps.silver.devops.gov.bc.ca/) available
---
Thanks for …
=> bugfix for sticky header with expanded filters

frontend/src/assets/sass/modals.scss
---
[Backend](https://nr-compliance-enforcement-146-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-146-frontend.apps.silver.devops.gov.bc.ca/) available
=> z-index updates for modals

frontend/src/app/components/codes/complaint-status-select.tsx, frontend/src/app/components/containers/complaints/complaint-details.tsx, frontend/src/app/store/reducers/complaints.ts
updated thunks to use axios api vs direct axios calls, removed global configuration of bearer token that may have been causing the jwt to expire and not refresh correctly
Fixes # COMPENF-861
---
[Backend](https://nr-compliance-enforcement-145-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-145-frontend.apps.silver.devops.gov.bc.ca/) available
=> Fixed false failing jwt guard

frontend/src/app/components/mapping/complaint-summary-popup.tsx, frontend/src/assets/sass/maps.scss
* For unassigned complaints, remove the initials
* Reduce spacing between "location/address" title and entry so it's clearer they are together
---
[Backend](https://nr-compliance-enforcement-147-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-147-frontend.apps.silver.devops.gov.bc.ca/) available
=> COMPENF-963-Map Popup UI Updates

frontend/src/app/components/containers/complaints/headers/allegation-complaint-list-header.tsx, frontend/src/app/components/containers/complaints/headers/wildlife-complaint-list-header.tsx, frontend/src/assets/sass/complaint.scss
---
[Backend](https://nr-compliance-enforcement-162-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-162-frontend.apps.silver.devops.gov.bc.ca/) available
=> Transition cursor to pointer on sortable headers

backend/db/migrations/R__Code-table-description-updates.sql, backend/src/v1/species_code/species_code.service.ts
---
[Backend](https://nr-compliance-enforcement-166-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-166-frontend.apps.silver.devops.gov.bc.ca/) available
=> Update Species Capitilization and Sort Order

frontend/src/assets/sass/complaint.scss, frontend/src/assets/sass/layout.scss, frontend/src/assets/sass/variables.scss, frontend/src/assets/sass/zone-at-a-glance.scss
---
[Backend](https://nr-compliance-enforcement-167-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-167-frontend.apps.silver.devops.gov.bc.ca/) available
=> Updates to hover state on complaint list

frontend/src/assets/sass/complaint.scss
---
[Backend](https://nr-compliance-enforcement-169-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-169-frontend.apps.silver.devops.gov.bc.ca/) available
=> Fix issue where expanding textarea overlaps parent

frontend/src/assets/sass/layout.scss
- [X ] New and existing unit tests pass locally with my changes
---
[Backend](https://nr-compliance-enforcement-176-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-176-frontend.apps.silver.devops.gov.bc.ca/) available
[Main Merge …
=> Update z-index of sidebar for small screens.

backend/src/types/constants.ts, backend/src/v1/allegation_complaint/allegation_complaint.controller.ts, backend/src/v1/allegation_complaint/allegation_complaint.service.spec.ts, backend/src/v1/allegation_complaint/allegation_complaint.service.ts, backend/src/v1/allegation_complaint/allegation_complaint.service.v2.spec.ts, backend/src/v1/complaint/models/search-payload.ts, backend/src/v1/hwcr_complaint/hwcr_complaint.controller.ts, backend/src/v1/hwcr_complaint/hwcr_complaint.service.ts, backend/src/v1/hwcr_complaint/hwcr_complaint.service.v2.spec.ts, backend/test/mocks/mock-allegation-complaint-repository.ts, backend/test/mocks/mock-wildlife-conflict-complaint-repository.ts, frontend/cypress/e2e/complaint-search.v2.cy.ts
Refactor hwcr_complaint and allegation_complaint api's to reduce controller complexity, and duplicated code in the services
Fixes # CE-190
Existing unit tests have been updated to satisfy refactoring
---
[Backend](https://nr-compliance-enforcement-177-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-177-frontend.apps.silver.devops.gov.bc.ca/) available
--- …
=> Refactoring wildlife and allegation api

frontend/src/assets/sass/misc.scss
---
[Backend](https://nr-compliance-enforcement-180-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-180-frontend.apps.silver.devops.gov.bc.ca/) available
=> Add z-index to tooltips.

frontend/src/app/common/validation-textarea.tsx, frontend/src/app/components/containers/complaints/details/complaint-details-create.tsx, frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx
---
[Backend](https://nr-compliance-enforcement-183-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-183-frontend.apps.silver.devops.gov.bc.ca/) available
=> input length limits

frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx
---
[Backend](https://nr-compliance-enforcement-190-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-190-frontend.apps.silver.devops.gov.bc.ca/) available
=> scroll to top of page on edit

frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx, frontend/src/app/components/containers/complaints/list-items/allegation-complaint-list-item.tsx, frontend/src/app/components/containers/complaints/list-items/wildlife-complaint-list-item.tsx, frontend/src/app/store/reducers/complaints.ts
---
[Backend](https://nr-compliance-enforcement-191-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-191-frontend.apps.silver.devops.gov.bc.ca/) available
=> Allow for empty or unknown communities

frontend/cypress/e2e/change-complaint-assignee.cy.ts, frontend/cypress/e2e/change-complaint-status.cy.ts, frontend/package-lock.json, frontend/package.json, frontend/src/app/common/methods.tsx, frontend/src/app/components/containers/complaints/complaint-list.tsx, frontend/src/app/components/containers/complaints/headers/allegation-complaint-list-header.tsx, frontend/src/app/components/containers/complaints/headers/wildlife-complaint-list-header.tsx, frontend/src/app/components/containers/complaints/list-items/allegation-complaint-list-item.tsx, frontend/src/app/components/containers/complaints/list-items/complaint-action-items.tsx, frontend/src/app/components/containers/complaints/list-items/wildlife-complaint-list-item.tsx, frontend/src/assets/sass/complaint.scss, frontend/src/assets/sass/misc.scss
As an officer I want to be able to easily view a summary of the complaint from the list view so that I can quickly make decisions around priority/assignment without viewing the full details of the complaint
Fixes CE-7
---
[Backend](https://nr-compliance-enforcement-195-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-195-frontend.apps.silver.devops.gov.bc.ca/) available
[Main Merge …
=> feature/CE-7 Expanded View of a Complaint in List View 

frontend/src/app/store/reducers/complaints.ts
---
[Backend](https://nr-compliance-enforcement-201-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-201-frontend.apps.silver.devops.gov.bc.ca/) available
=> Geocode address

frontend/src/app/components/modal/instances/assign-officer-modal.tsx, frontend/src/assets/sass/layout.scss
---
[Backend](https://nr-compliance-enforcement-212-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-212-frontend.apps.silver.devops.gov.bc.ca/) available
=> Adding hover state

frontend/src/assets/sass/carousel.scss
---
[Backend](https://nr-compliance-enforcement-214-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-214-frontend.apps.silver.devops.gov.bc.ca/) available
=> Hide carousel buttons when not required

frontend/src/app/components/mapping/leaflet-map-with-multiple-points.tsx
---
[Backend](https://nr-compliance-enforcement-215-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-215-frontend.apps.silver.devops.gov.bc.ca/) available
=> check for pluralization of complaint on map banner

frontend/src/app/components/containers/complaints/list-items/allegation-complaint-list-item.tsx, frontend/src/app/components/containers/complaints/list-items/wildlife-complaint-list-item.tsx, frontend/src/assets/sass/complaint.scss
---
[Backend](https://nr-compliance-enforcement-216-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-216-frontend.apps.silver.devops.gov.bc.ca/) available
=> Protection against long data on list view

frontend/cypress/e2e/complaints-on-map-view.cy.ts, frontend/src/app/components/mapping/complaint-summary-popup.tsx
---
[Backend](https://nr-compliance-enforcement-218-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-218-frontend.apps.silver.devops.gov.bc.ca/) available
=> Popup on map should be community + tests

.github/workflows/pr-open.yml, backend/package-lock.json, frontend/package-lock.json, frontend/package.json
Fixes CE-349
---
[Backend](https://nr-compliance-enforcement-227-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-227-frontend.apps.silver.devops.gov.bc.ca/) available
=> Bump Babel Traverse to latest minor version

backend/package-lock.json, frontend/package-lock.json, frontend/package.json
CE-350
CE-351
CE-353
CE-355
---
[Backend](https://nr-compliance-enforcement-229-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-229-frontend.apps.silver.devops.gov.bc.ca/) available
[Main Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement/actions/workflows/merge- …
=> Dependency Upgrades

frontend/package-lock.json, frontend/package.json
Fixes # CE-354
---
[Backend](https://nr-compliance-enforcement-232-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-232-frontend.apps.silver.devops.gov.bc.ca/) available
=> Upgrade Cypress to v13

frontend/src/app/store/reducers/complaints.ts
Missed edge case when complaint has no assignee, which was causing the refresh to fail
Fixes # CE-324
Existing tests covered 
---
[Backend](https://nr-compliance-enforcement-234-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-234-frontend.apps.silver.devops.gov.bc.ca/) available
=> bug/CE-324 UPDATE

backend/src/v1/complaint/complaint.service.ts
Fixes # CE-327
---
[Backend](https://nr-compliance-enforcement-237-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-237-frontend.apps.silver.devops.gov.bc.ca/) available
=> Add current user to update audit fields

backend/db/migrations/R__Create-Test-Data.sql
---
[Backend](https://nr-compliance-enforcement-242-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-242-frontend.apps.silver.devops.gov.bc.ca/) available
=> Add Scarlett and Dragos to user table

backend/src/types/models/code-tables/index.ts, backend/src/types/models/code-tables/prevent-education-action.ts, backend/src/v1/code-table/code-table.service.ts, frontend/src/app/components/containers/complaints/outcomes/hwcr-prevention-education.tsx, frontend/src/app/constants/code-table-types.ts, frontend/src/app/store/reducers/code-table.ts, frontend/src/app/types/app/code-tables/prevent-education-action.ts, frontend/src/app/types/state/code-table-state.ts, frontend/src/assets/sass/outcome-report.scss
---
[Backend](https://nr-compliance-enforcement-249-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-249-frontend.apps.silver.devops.gov.bc.ca/) available
=> feat: CE-363-Add Prevent and Education

.github/workflows/deploy-nats.yml, frontend/src/app/components/containers/complaints/outcomes/hwcr-complaint-assessment.tsx
Adds the comp-select class to the dropdowns in the Complaint Assessment to ensure proper focus styling
---
[Backend](https://nr-compliance-enforcement-250-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-250-frontend.apps.silver.devops.gov.bc.ca/) available
=> Bug: Selected states for drop down in HWCR assessment

frontend/src/app/components/containers/complaints/outcomes/hwcr-complaint-assessment.tsx, frontend/src/app/components/containers/complaints/outcomes/hwcr-prevention-education.tsx
---
[Backend](https://nr-compliance-enforcement-251-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-251-frontend.apps.silver.devops.gov.bc.ca/) available
=> fix: cannot change officer in Complaint Assessment

.github/workflows/deploy-nats.yml, .github/workflows/merge-main.yml, .github/workflows/pr-close.yml
NATS container now being cleaned up on closing of PR
HELM project being cleaned up on closing PR
NATS and HELM should now be migrating to TEST when closing (and merging) a PR
---
[Backend](https://nr-compliance-enforcement-254-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-254-frontend.apps.silver.devops.gov.bc.ca/) available
[Main Merge …
=> feat: improvements to NATS and WebEOC in pipeline

.github/workflows/merge-main.yml
NATS is now part of the test-deployment but it occurs before the other containers start.
Unable to test until a test migration is processed.
---
[Backend](https://nr-compliance-enforcement-256-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-256-frontend.apps.silver.devops.gov.bc.ca/) available
=> bug: reorder deployments

.github/workflows/merge-main.yml
Fixing syntax issue on deployment of NATS to test
---
[Backend](https://nr-compliance-enforcement-257-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-257-frontend.apps.silver.devops.gov.bc.ca/) available
=> bug: NATS in test issue

.github/workflows/merge-main.yml
Fixing issue with deploying NATS in test
---
[Backend](https://nr-compliance-enforcement-259-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-259-frontend.apps.silver.devops.gov.bc.ca/) available
=> bug: NATS order issue

frontend/src/app/components/containers/complaints/details/complaint-details-create.tsx
Updates the create complaint component to correctly handle invalid form data. When empty form is submitted, no complaint is created. When missing data filled in correctly the create complaint component correctly submits new complaint
Fixes # CE-416
- Existing tests should cover this
---
[Backend](https://nr-compliance-enforcement-263-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-263-frontend.apps.silver.devops.gov.bc.ca/) available
=> bug/CE-416 

.github/workflows/merge-main.yml, docker-compose.yml, webeoc/openshift.deploy.yml
The test environment was close to capacity in terms of resources, which limited options for horizontal scaling.  This PR reduces the limits for the NATS container.
---
[Backend](https://nr-compliance-enforcement-267-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-267-frontend.apps.silver.devops.gov.bc.ca/) available
=> feat: Changed resource limits in test

frontend/src/assets/sass/outcome-report.scss
Fixes # CE-414
---
[Backend](https://nr-compliance-enforcement-268-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-268-frontend.apps.silver.devops.gov.bc.ca/) available
=> Changed style on hidden field

.github/workflows/schemaspy.yaml
1. Removed deprecated GHA(https://github.com/joshuaavalon/flyway-action)
2. Fix the error during workflow run https://github.com/bcgov/nr-compliance-enforcement/actions/runs/7674137896/job/20918154521#step:7:66
---
[Backend](https://nr-compliance-enforcement-269-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-269-frontend.apps.silver.devops.gov.bc.ca/) available
=> fix: schema-spy

frontend/src/app/common/validation-textarea.tsx, frontend/src/app/components/common/comp-select.tsx, frontend/src/app/components/containers/complaints/outcomes/hwcr-complaint-assessment.tsx, frontend/src/app/components/containers/complaints/outcomes/hwcr-outcome-report.tsx, frontend/src/app/components/containers/complaints/outcomes/hwcr-supplemental-notes.tsx, frontend/src/assets/sass/complaint.scss, frontend/src/assets/sass/layout.scss, frontend/src/assets/sass/misc.scss, frontend/src/assets/sass/outcome-report.scss
---
[Backend](https://nr-compliance-enforcement-270-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-270-frontend.apps.silver.devops.gov.bc.ca/) available
=> Supporting Notes changes

frontend/cypress/e2e/allegation-details-create.cy.ts, frontend/cypress/e2e/allegation-details-edit.cy.ts, frontend/cypress/e2e/allegation-details.cy.ts, frontend/cypress/e2e/change-complaint-assignee-details-view.cy.ts, frontend/cypress/e2e/change-complaint-status-details-view.cy.ts, frontend/cypress/e2e/complaint-attachments.cy.ts, frontend/cypress/e2e/hwcr-details-edit.cy.ts, frontend/cypress/e2e/hwcr-details.cy.ts, frontend/cypress/e2e/sticky-headers.cy.ts, frontend/cypress/support/commands.ts, frontend/cypress/support/index.ts
---
[Backend](https://nr-compliance-enforcement-286-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-286-frontend.apps.silver.devops.gov.bc.ca/) available
=> Add cypress option to direct nav to complaint.

frontend/src/app/components/containers/complaints/outcomes/hwcr-equipment/equipment-item.tsx, frontend/src/assets/sass/hwcr-equipment.scss
CE-524: Hover state for edit button in equipment section
---
[Backend](https://nr-compliance-enforcement-294-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-294-frontend.apps.silver.devops.gov.bc.ca/) available
[Main Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement/actions/wor …
=> CE-524: Update equipment view styles

frontend/src/app/components/containers/complaints/outcomes/animal-outcomes/animal-outcome-item.tsx
CE-525: Animal info badges
---
[Backend](https://nr-compliance-enforcement-295-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-295-frontend.apps.silver.devops.gov.bc.ca/) available
=> Remove supporting width from outcome header

frontend/src/app/common/methods.tsx, frontend/src/app/components/common/attachments-carousel.tsx, frontend/src/app/store/reducers/attachments.ts, frontend/src/assets/sass/carousel.scss
CE-527: Unable to remove pending images
CE-528: Unable to upload TIF / TIFF files
---
[Backend](https://nr-compliance-enforcement-297-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-297-frontend.apps.silver.devops.gov.bc.ca/) available
[Main Merge …
=> Remove tif/f from image types and errorhandling++

frontend/src/assets/sass/layout.scss
Updated the css to position the clear button on the assign officer modal to position top vs bottom as was originally done
---
[Backend](https://nr-compliance-enforcement-299-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-299-frontend.apps.silver.devops.gov.bc.ca/) available
=> bug/CE-530: clear button position incorrect

frontend/src/app/components/common/comp-text-icon-button.tsx, frontend/src/app/components/containers/complaints/outcomes/hwcr-equipment/equipment-item.tsx, frontend/src/app/components/containers/complaints/outcomes/hwcr-equipment/index.tsx, frontend/src/app/components/modal/instances/delete-confirm-modal.tsx, frontend/src/assets/sass/complaint.scss
---
[Backend](https://nr-compliance-enforcement-303-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-303-frontend.apps.silver.devops.gov.bc.ca/) available
=> feat/CE-41-Delete Equipment UI

.github/workflows/pr-open.yml, backend/openshift.deploy.yml, database/openshift.deploy.yml
Parameterized CPU limits and requests for the database.  Updated limits and requests on Pull Requests (test remains unchanged).
---
[Backend](https://nr-compliance-enforcement-304-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-304-frontend.apps.silver.devops.gov.bc.ca/) available
---
[Backend](https://nr-compliance-enforcement-304-backend.apps.silver.devops.gov.bc. …
=> feat: CE-429 - Openshift limit updates

frontend/cypress/e2e/complaints-on-map-view.cy.ts, frontend/src/app/components/containers/complaints/complaint-map.tsx, frontend/src/app/components/mapping/leaflet-map-with-multiple-points.tsx, frontend/src/assets/sass/complaint.scss
Update to the map component to allow the system to display message when no search results are found
Story # CE-514
---
[Backend](https://nr-compliance-enforcement-308-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-308-frontend.apps.silver.devops.gov.bc.ca/) available
=> feat/CE-514: add banner to map view

frontend/src/app/components/containers/complaints/details/complaint-details-create.tsx
Fixes # CE-583
---
[Backend](https://nr-compliance-enforcement-324-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-324-frontend.apps.silver.devops.gov.bc.ca/) available
=> Add container and title for create attachments

frontend/src/app/store/store.ts
---
[Backend](https://nr-compliance-enforcement-336-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-336-frontend.apps.silver.devops.gov.bc.ca/) available
=> fix: CE-600 bump redux ver

.github/workflows/pr-open.yml, backend/openshift.deploy.yml, backend/src/types/models/case-files/supplemental-notes/equipment/delete-equipment-dto.ts, backend/src/types/models/case-files/supplemental-notes/equipment/equipment-details.ts, backend/src/v1/case_file/case_file.controller.ts, backend/src/v1/case_file/case_file.service.ts, common/openshift.init.yml, frontend/src/app/common/validation-date-picker.tsx, frontend/src/app/components/containers/complaints/outcomes/hwcr-equipment/equipment-form.tsx, frontend/src/app/components/containers/complaints/outcomes/hwcr-equipment/equipment-item.tsx, frontend/src/app/components/containers/complaints/outcomes/hwcr-equipment/index.tsx, frontend/src/app/store/reducers/case-thunks.ts, frontend/src/app/types/app/case-files/equipment-details.ts, frontend/src/app/types/app/case-files/equipment-inputs/delete-equipment-input.ts
Updated variable names
Users can now set the "Removed By" user of a piece of equipment, as part of an update.
---
[Backend](https://nr-compliance-enforcement-342-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-342-frontend.apps.silver.devops.gov.bc.ca/) available
---
[Backend](https://nr-compliance-enforcement-342-backend.apps.silver.devops.gov.bc.ca/) available …
=> fix: CE-615

.github/workflows/merge-main.yml, .github/workflows/pr-open.yml
---
[Backend](https://nr-compliance-enforcement-346-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-346-frontend.apps.silver.devops.gov.bc.ca/) available
=> Bump action deployer to latest

.github/workflows/merge-main.yml
---
[Backend](https://nr-compliance-enforcement-356-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-356-frontend.apps.silver.devops.gov.bc.ca/) available
=> Temporarily turn of zap to get deploys moving

frontend/src/app/components/containers/complaints/outcomes/animal-outcomes/edit-animal-outcome.tsx
---
[Backend](https://nr-compliance-enforcement-345-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-345-frontend.apps.silver.devops.gov.bc.ca/) available
=> fix: CE-609 Animal drugs save with missing mandatory fields

common/openshift.init.yml
---
[Backend](https://nr-compliance-enforcement-374-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-374-frontend.apps.silver.devops.gov.bc.ca/) available
=> defaults initial value of case management api to dev static in dev

frontend/src/app/components/containers/complaints/complaints.tsx
---
[Backend](https://nr-compliance-enforcement-409-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-409-frontend.apps.silver.devops.gov.bc.ca/) available
=> fix: CE-92 default zone not showing the first time

frontend/cypress/e2e/hwcr-outcome-assessment.cy.ts, frontend/cypress/e2e/hwcr-outcome-prev-and-educ.cy.ts, frontend/cypress/support/commands.ts, frontend/cypress/support/index.ts
---
[Backend](https://nr-compliance-enforcement-405-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-405-frontend.apps.silver.devops.gov.bc.ca/) available
=> Updates to Assessment and P&E Cypress tests

frontend/src/app/components/common/map-list-toggle.tsx, frontend/src/assets/sass/complaint.scss
This PR adds labels to toggle/button between the list and map view
Fixes # (CE-632)
---
[Backend](https://nr-compliance-enforcement-408-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-408-frontend.apps.silver.devops.gov.bc.ca/) available
=> feature/CE-632-Add-labels-to-toggle/button-between-list-and-map-view 

frontend/src/app/components/containers/complaints/details/complaint-details-create.tsx
---
[Backend](https://nr-compliance-enforcement-410-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-410-frontend.apps.silver.devops.gov.bc.ca/) available
=> fix: CE-607 single attractant is not saved on create

frontend/package-lock.json, frontend/package.json, frontend/src/app/components/mapping/leaflet-map-with-multiple-points.tsx, frontend/src/app/components/mapping/leaflet-map-with-point.tsx, frontend/src/app/components/mapping/map-gesture-handler.tsx
---
[Backend](https://nr-compliance-enforcement-411-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-411-frontend.apps.silver.devops.gov.bc.ca/) available
=> feat: CE-636 allow user to scroll through map

frontend/src/app/components/common/attachment-slide.tsx
This PR updates the ‘Pending Upload’ text for attachments waiting on a save by "Save to upload attachment(s)"
It affects both Complaint and Outcome attachment sections.
Fixes # (CE-628)
---
[Backend](https://nr-compliance-enforcement-412-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-412-frontend.apps.silver.devops.gov.bc.ca/) available
[Main Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement/ …
=> feature/CE-628-Update-"Pending-Upload"-text-on-attachments-waiting-to-be-saved Change text

.github/workflows/pr-open.yml, .github/workflows/unit-tests.yml, backend/package-lock.json, database/Dockerfile, database/postgis/Dockerfile, docker-compose.yml, frontend/Dockerfile, frontend/package-lock.json, webeoc/package-lock.json
Consolidation of library updates.
---
[Backend](https://nr-compliance-enforcement-414-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-414-frontend.apps.silver.devops.gov.bc.ca/) available
---
[Backend](https://nr-compliance-enforcement-414-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-414-frontend.apps.silver.devops.gov.bc.ca/) …
=> chore: CE-645 renovate updates

.github/workflows/merge-main.yml
Add pipeline updates to promote NATS/Jetstream to test environment.
---
[Backend](https://nr-compliance-enforcement-415-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-415-frontend.apps.silver.devops.gov.bc.ca/) available
=> chore: CE-491 NATS Pipeline Updates for Test

backend/src/v1/complaint/complaint.service.ts
---
[Backend](https://nr-compliance-enforcement-416-backend.apps.silver.devops.gov.bc.ca/) available
[Frontend](https://nr-compliance-enforcement-416-frontend.apps.silver.devops.gov.bc.ca/) available
---
[Backend](https://nr-compliance-enforcement-416-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-416-frontend.apps.silver.devops.gov.bc.ca/) available
Once merged, code will …
=> fix: CE-656 zone at glance not display all officers

webeoc/src/webeoc-complaints-scheduler/webeoc-complaints-scheduler.service.ts
---
[Backend](https://nr-compliance-enforcement-421-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-421-frontend.apps.silver.devops.gov.bc.ca/) available
=> chore: Update webEOC Incident URL

webeoc/src/webeoc-complaints-scheduler/webeoc-complaints-scheduler.service.ts
Fixes # CE-658
---
[Backend](https://nr-compliance-enforcement-422-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-422-frontend.apps.silver.devops.gov.bc.ca/) available
=> feat: webEOC filter now uses entryDate and pilot flag

backend/db/migrations/R__Code-Tables.sql, backend/db/migrations/V0.19.6__CE-503.sql, backend/src/types/models/code-tables/complaint-status.ts, backend/src/v1/code-table/code-table.service.ts, backend/src/v1/complaint_status_code/entities/complaint_status_code.entity.ts, frontend/src/app/types/app/code-tables/complaint-status.ts
Updates to COMPLAINT_STATUS_CODE table:
Made short descriptions Title Case
Added PENDREV (Pending Review)
Set order of CLOSED to 3
---
[Backend](https://nr-compliance-enforcement-424-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-424-frontend.apps.silver.devops.gov.bc.ca/) available
=> feat: CE-716 - Add Pending Review Complaint Status Code

frontend/src/app/components/containers/complaints/details/call-details.tsx, frontend/src/app/components/containers/complaints/outcomes/supplemental-notes/supplemental-notes-item.tsx, frontend/src/assets/sass/layout.scss
Fixes # CE-602
---
[Backend](https://nr-compliance-enforcement-430-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-430-frontend.apps.silver.devops.gov.bc.ca/) available
=> fix: CE-602: Fixed word wrapping on Complaint Details and notes

frontend/src/setupTests.ts, webeoc/src/common/constants.ts
---
[Backend](https://nr-compliance-enforcement-434-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-434-frontend.apps.silver.devops.gov.bc.ca/) available
=> kickstarting webeoc and frontend

backend/db/migrations/R__0.14.0__CE-101.sql, backend/db/migrations/R__0.19.2__log_complaint_update.sql, backend/db/migrations/R__0.19.3__update_complaint_using_webeoc_update.sql, backend/db/migrations/R__0.20.0_edit_complaint_using_webeoc_complaint.sql, backend/db/migrations/R__Code-Tables.sql, backend/src/enum/staging_activity_code.enum.ts, backend/src/v1/staging_complaint/staging_complaint.controller.ts, backend/src/v1/staging_complaint/staging_complaint.service.ts, webeoc/src/complaints-publisher/complaints-publisher.service.ts, webeoc/src/staging-complaints-api-service/staging-complaints-api-service.service.ts
Receive Edits to HWCs and ECs from WebEOC
---
[Backend](https://nr-compliance-enforcement-446-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-446-frontend.apps.silver.devops.gov.bc.ca/) available
=> feat: CE-450 receive edits from web eoc

.github/workflows/merge-main.yml
---
[Backend](https://nr-compliance-enforcement-452-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-452-frontend.apps.silver.devops.gov.bc.ca/) available
=> fix error in merge-main

.github/workflows/merge-main.yml
---
[Backend](https://nr-compliance-enforcement-453-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-453-frontend.apps.silver.devops.gov.bc.ca/) available
=> remove line from merge-main

backend/db/migrations/R__Create-Test-Data.sql, backend/db/test-only-migrations/R__Test-Data-Creation.sql
---
[Backend](https://nr-compliance-enforcement-456-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-456-frontend.apps.silver.devops.gov.bc.ca/) available
=> Updates to guids in test scripts for offices

.github/workflows/merge-main.yml
Database wasn't being correctly deployed in test and prod.  This fixes that.
Will need to test via pipeline
---
[Backend](https://nr-compliance-enforcement-460-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-460-frontend.apps.silver.devops.gov.bc.ca/) available
=> bug: Pipeline Deployment issue with Database 

frontend/src/app/common/validation-checkbox-group.tsx, frontend/src/app/components/containers/complaints/outcomes/hwcr-complaint-assessment.tsx, frontend/src/app/components/containers/complaints/outcomes/hwcr-outcome-report.tsx, frontend/src/assets/sass/complaint.scss, frontend/src/assets/sass/form.scss, frontend/src/assets/sass/layout.scss, frontend/src/assets/sass/outcome-report.scss
- Refactored Outcome Assessment Form and Details View
- Quick pass over remaining outcome form items to ensure the layout doesn't look entirely busted until we get through the remainder of the components.
---
[Backend](https://nr-compliance-enforcement-462-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-462-frontend.apps.silver.devops.gov.bc.ca/) available
[Main Merge …
=> CE-796 - Refactor Outcome Assessment Form and Details View

frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx, frontend/src/app/components/containers/complaints/outcomes/hwcr-complaint-assessment.tsx, frontend/src/app/components/containers/complaints/outcomes/hwcr-outcome-report.tsx, frontend/src/app/components/containers/complaints/outcomes/hwcr-prevention-education.tsx, frontend/src/assets/sass/complaint.scss, frontend/src/assets/sass/outcome-report.scss
- Refactor the Prevention and Education Details and Form
---
[Backend](https://nr-compliance-enforcement-465-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-465-frontend.apps.silver.devops.gov.bc.ca/) available
=> CE-810 - Refactor Prevention and Education Details and Form

frontend/src/assets/sass/complaint.scss
- Minor styling fix to correct the background color for the pending review badge.
---
[Backend](https://nr-compliance-enforcement-466-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-466-frontend.apps.silver.devops.gov.bc.ca/) available
=> CE-785 - Fix Pending Status Badge Background Color

backend/db/migrations/R__0.14.0__CE-101.sql, backend/db/migrations/R__0.19.3__update_complaint_using_webeoc_update.sql, backend/db/migrations/R__0.20.0_edit_complaint_using_webeoc_complaint.sql
---
[Backend](https://nr-compliance-enforcement-468-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-468-frontend.apps.silver.devops.gov.bc.ca/) available
=> feat/CE-736 handle HWCR ERS of specific types

frontend/index.html, frontend/public/index.html
---
[Backend](https://nr-compliance-enforcement-471-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-471-frontend.apps.silver.devops.gov.bc.ca/) available
=> chore: CE-783 give app proper description

webeoc/openshift.deploy.yml, webeoc/package-lock.json, webeoc/package.json, webeoc/src/main.ts, webeoc/src/webeoc-complaints-scheduler/webeoc-complaints-scheduler.service.ts
We could only grab the complaint history where the complaints were older than x days (where x is supplied via an environment variable).  This is now in seconds.
Currently the webEOC polling interval is set to 1 Day (24 hours)
Due to concerns about the load on the webEOC APIs, the webEOC team has requested this is reduced to 10 minutes.   This will require the following changes:
configuration parameter webeoc-complaint-history-days will need to be renamed webeoc-complaint-history-minutes
The value will need to be changed from 1 (day) to 600 (seconds - or 10 minutes)
The time logic in the webEOC scheduler will need to be updated to reflect that change in granularity from Days to Seconds
Please describe the tests that you ran to verify your changes. Provide instructions so we …
=> feat: CE-792 Adjust webEOC Poll Interval

frontend/src/app/components/common/comp-radiogroup.tsx, frontend/src/app/components/containers/complaints/outcomes/hwcr-equipment/equipment-form.tsx, frontend/src/app/components/containers/complaints/outcomes/hwcr-equipment/equipment-item.tsx, frontend/src/app/components/containers/complaints/outcomes/hwcr-equipment/index.tsx, frontend/src/assets/sass/complaint.scss, frontend/src/assets/sass/form.scss, frontend/src/assets/sass/layout.scss, frontend/src/assets/sass/outcome-report.scss
Refactored the details and form interfaces for the equipment section of the outcome report.
---
[Backend](https://nr-compliance-enforcement-469-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-469-frontend.apps.silver.devops.gov.bc.ca/) available
=> CE-687 - Refactor Equipment Details and Form

frontend/cypress/e2e/change-complaint-status.cy.ts, frontend/cypress/e2e/hwcr-outcome-review.cy.ts
This PR contains Cypress tests for the File Review feature CE-503
Fixes # (CE-721)
---
[Backend](https://nr-compliance-enforcement-459-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-459-frontend.apps.silver.devops.gov.bc.ca/) available
=> chore: CE-721-Cypress-Tests-for-CE-503

backend/db/migrations/R__Create-Test-Data.sql, backend/db/test-only-migrations/R__Test-Data-Creation.sql
---
[Backend](https://nr-compliance-enforcement-474-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-474-frontend.apps.silver.devops.gov.bc.ca/) available
=> chore: Add pilot users to scripts so they will be in test and prod

frontend/src/app/components/containers/complaints/outcomes/hwcr-file-review.tsx
---
[Backend](https://nr-compliance-enforcement-478-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-478-frontend.apps.silver.devops.gov.bc.ca/) available
=> fix: CE-822 closing complaint-error disappears when review complete checked

backend/src/external_api/cdogs/cdogs.service.ts
---
[Backend](https://nr-compliance-enforcement-477-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-477-frontend.apps.silver.devops.gov.bc.ca/) available
=> fix: document generation failing on first run

frontend/src/app/components/containers/complaints/outcomes/hwcr-supplemental-notes.tsx, frontend/src/app/components/containers/complaints/outcomes/supplemental-notes/supplemental-notes-input.tsx, frontend/src/app/components/containers/complaints/outcomes/supplemental-notes/supplemental-notes-item.tsx, frontend/src/assets/sass/outcome-report.scss
- Refactor additional notes details and forms
---
[Backend](https://nr-compliance-enforcement-476-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-476-frontend.apps.silver.devops.gov.bc.ca/) available
=> CE-811 - Refactor Additional Notes Details and Form

frontend/cypress/e2e/complaint-attachments.cy.ts, frontend/cypress/support/commands.ts, frontend/src/app/components/common/attachment-slide.tsx, frontend/src/app/components/common/attachment-upload.tsx, frontend/src/app/components/common/attachments-carousel.tsx, frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx, frontend/src/app/components/containers/complaints/outcomes/hwcr-file-attachments.tsx, frontend/src/assets/sass/carousel.scss
Refactoring the attachments interface to support smaller devices.
As discussed with the design team, this refactor is to get us out of the gate with a more useful layout for the attachments that can scale up and down as needed. Future consideration for alternative designs to better support users will need to be addressed when more data is gathered through user testing / feedback.
---
[Backend](https://nr-compliance-enforcement-482-frontend.apps.silver.devops.gov.bc.ca/api/) available …
=> CE-798 - Mobile Refactor for Attachments Interfaces

frontend/src/app/store/reducers/officer.ts
This PR fixes a bug when COS HQ Officer Appear in Outcome By Animal Section.
Fixes # (CE-850)
---
[Backend](https://nr-compliance-enforcement-486-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-486-frontend.apps.silver.devops.gov.bc.ca/) available
=> bug: CE-850-COS-HQ-Officer-Appear-in-Outcome-By-Animal-Section

frontend/src/app/components/containers/complaints/webeoc-complaint-updates/webeoc-complaint-update-list.tsx, frontend/src/assets/sass/complaint.scss
---
[Backend](https://nr-compliance-enforcement-489-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-489-frontend.apps.silver.devops.gov.bc.ca/) available
=> fix: update banners width should match the rest

frontend/src/app/components/containers/complaints/outcomes/hwcr-complaint-assessment.tsx, frontend/src/app/components/containers/complaints/outcomes/hwcr-prevention-education.tsx
---
[Backend](https://nr-compliance-enforcement-490-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-490-frontend.apps.silver.devops.gov.bc.ca/) available
=> fix: issue with closing validation message in Prevention

frontend/src/app/store/reducers/case-thunks.ts
---
[Backend](https://nr-compliance-enforcement-491-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-491-frontend.apps.silver.devops.gov.bc.ca/) available
=> fix: delete equipment makes animal disappear

frontend/src/app/store/reducers/complaints.ts
Modifies the number of complaints shown in the complaint type tab to include ALL complaints, and not just the mapped complaints
story # CE-852
---
[Backend](https://nr-compliance-enforcement-495-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-495-frontend.apps.silver.devops.gov.bc.ca/) available
=> feat: CE-852: update number of complaints in map view

backend/package-lock.json, frontend/package-lock.json, webeoc/package-lock.json
---
[Backend](https://nr-compliance-enforcement-492-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-492-frontend.apps.silver.devops.gov.bc.ca/) available
=> chore: update packages with high vulnerability

frontend/src/app/components/mapping/leaflet-map-with-multiple-points.tsx
Feedback from usability changes to the verbiage used to display unmapped complaints
Story #CE-747
- This is a UX Change, manually tested
---
[Backend](https://nr-compliance-enforcement-496-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-496-frontend.apps.silver.devops.gov.bc.ca/) available
=> feat: CE-747: update map verbiage

frontend/src/app/components/common/comp-select.tsx, frontend/src/app/components/containers/complaints/complaint-filter.tsx
---
[Backend](https://nr-compliance-enforcement-498-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-498-frontend.apps.silver.devops.gov.bc.ca/) available
=> feat: CE-772 add clear button for complaint filters

.github/workflows/merge-main.yml, .github/workflows/pr-open.yml, frontend/openshift.deploy.yml
[Frontend](https://nr-compliance-enforcement-500-frontend.apps.silver.devops.gov.bc.ca/) available -> I set show_experimental_features to "true" in Openshift dev. Feel free to toggle it to test
=> chore: CE-864 move Feature flag to OpenShift

backend/db/migrations/R__Create-Test-Data.sql
---
[Backend](https://nr-compliance-enforcement-513-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-513-frontend.apps.silver.devops.gov.bc.ca/) available
=> CE-890-community-move

frontend/src/app/store/reducers/documents-thunks.ts
Fixes # CE-894
---
[Backend](https://nr-compliance-enforcement-514-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-514-frontend.apps.silver.devops.gov.bc.ca/) available
=> Encode timezone to handle Peace Value

backend/src/middleware/maps/automapper-entity-to-dto-maps.ts, backend/src/types/models/complaints/complaint.ts, backend/src/types/models/complaints/update-complaint.dto.ts, backend/src/types/models/reports/complaints/complaint-report-data.ts, backend/src/v1/complaint/entities/complaint.entity.ts, backend/src/v1/complaint_updates/entities/complaint_updates.entity.ts, frontend/src/app/types/app/complaints/complaint.ts, frontend/src/app/types/app/complaints/webeoc-complaint-update.ts, webeoc/src/types/actions-taken/action-taken.ts
Provides updates to models, maps, and entity types
Task #CE-873
No testing required
---
[Backend](https://nr-compliance-enforcement-517-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-517-frontend.apps.silver.devops.gov.bc.ca/) available
=> feat: CE-873 - Update webEOC Complaint Incident Staging to Capture webEOC PK

backend/db/test-only-migrations/V23.0.0__CE-875.sql, backend/src/middleware/maps/automapper-entity-to-dto-maps.ts, frontend/src/app/components/containers/complaints/list-items/allegation-complaint-list-item.tsx, frontend/src/app/components/containers/complaints/list-items/wildlife-complaint-list-item.tsx, frontend/src/app/types/app/complaints/complaint.ts
---
[Backend](https://nr-compliance-enforcement-516-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-516-frontend.apps.silver.devops.gov.bc.ca/) available
=> fix: CE-875 ERS filter for dumping broken

frontend/cypress/e2e/complaints-on-map-view.cy.ts, frontend/src/app/components/mapping/complaint-summary-popup.tsx, frontend/src/assets/sass/maps.scss
---
[Backend](https://nr-compliance-enforcement-512-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-512-frontend.apps.silver.devops.gov.bc.ca/) available
=> CE-868 - Update Map Popup Layout

backend/src/v1/case_file/case_file.service.ts
Fixes # CE-898
---
[Backend](https://nr-compliance-enforcement-519-frontend.apps.silver.devops.gov.bc.ca/api/) available
[Frontend](https://nr-compliance-enforcement-519-frontend.apps.silver.devops.gov.bc.ca/) available
=> chore: Reduce Severity of Logging Message

.github/workflows/merge-hotfix.yml, backend/src/main.ts
---
- [Frontend](https://nr-compliance-enforcement-531-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-531-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> feat: C-905 hotfix pipeline updates

.github/workflows/merge-hotfix.yml, backend/src/main.ts
Fixed hotfix github action
---
- [Frontend](https://nr-compliance-enforcement-533-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-533-frontend.apps.silver.devops.gov.bc.ca/api)
---
- [Frontend](https://nr-compliance-enforcement-533-frontend.apps.silver.devops.gov.bc.ca)
- …
=> feat: CE-905 Hotfix

frontend/src/index.tsx
---
- [Frontend](https://nr-compliance-enforcement-534-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-534-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore: release-solve conflicts merge main

.github/workflows/analysis.yml, backend/package.json, charts/app/values.yaml
Set smaller resource limits on nats by default.
---
- [Frontend](https://nr-compliance-enforcement-535-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-535-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: Update Nats resource limits

.github/workflows/analysis.yml, .github/workflows/merge-release.yml, backend/src/main.ts, charts/app/values.yaml
Reduce nats resource limits
Change branch pattern from release/** to release/* on merge-release
---
- [Frontend](https://nr-compliance-enforcement-536-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-536-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> feat: Pipeline fixes

backend/src/main.ts
---
- [Frontend](https://nr-compliance-enforcement-541-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-541-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: Fix pr pipeline

.github/actions/get-pr-number/action.yml
---
- [Frontend](https://nr-compliance-enforcement-542-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-542-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: Update action.yml

backend/src/main.ts
---
- [Frontend](https://nr-compliance-enforcement-543-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-543-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: Kickstart test release

.github/workflows/merge-release.yml, backend/src/main.ts
---
- [Frontend](https://nr-compliance-enforcement-544-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-544-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: Fix pr issue round 6

.github/workflows/analysis.yml, .github/workflows/merge-hotfix.yml, .github/workflows/pr-close.yml, webeoc/src/main.ts
---
- [Frontend](https://nr-compliance-enforcement-545-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-545-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: applying PR fix to hotfix action

.github/actions/get-pr-number/action.yml
---
- [Frontend](https://nr-compliance-enforcement-546-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-546-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: hotfix PR numbering

.github/actions/get-pr-number/action.yml, .github/workflows/merge-release.yml, webeoc/src/main.ts
---
- [Frontend](https://nr-compliance-enforcement-547-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-547-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: Fix pr number in hotfix round2

webeoc/src/main.ts
---
- [Frontend](https://nr-compliance-enforcement-556-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-556-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: Kickstart builds

backend/src/types/models/complaints/dtoAlias-type.ts, backend/src/v1/complaint/complaint.controller.ts, frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx, frontend/src/app/components/containers/complaints/headers/general-complaint-list-header.tsx, frontend/src/app/components/containers/complaints/list-items/general-complaint-list-item.tsx, frontend/src/app/store/reducers/complaints.ts, frontend/src/app/store/reducers/officer.ts
Fixes for CE-952, CE-953, CE-954, CE-955
---
- [Frontend](https://nr-compliance-enforcement-565-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-565-frontend.apps.silver.devops.gov.bc.ca/api)
After merge, new images are …
=> fix: Ce 954 gir fixes

frontend/src/app/components/mapping/complaint-summary-popup.tsx
Fixed the display of the general incident type in the map popup component.
---
- [Frontend](https://nr-compliance-enforcement-567-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-567-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement/action …
=> feat: CE-969 - Fix GIR Map Popup Information

frontend/src/app/components/common/comp-input.tsx, frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/animal-outcome.tsx, frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/drug-authorized-by.tsx, frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/drug-used.tsx
Minor fixes for the 'Outcome by Animal' details and form components, including:
- Updated the display to include 'Unknown Sex' and 'Unknown Age' when specified in the form as 'Unknown'
- Updated the  'comp-input' control to include min and max properties when input type is number
- Updated “Drugs authorized by” text to be “Drugs administered by”.
---
- [Frontend](https://nr-compliance-enforcement-570-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-570-frontend.apps.silver.devops.gov.bc.ca/api)
Please …
=> feat: CE-967 - Minor Updates for Outcome by Animal Details and Form

frontend/src/app/components/common/comp-select.tsx
The react-select module has some bizarre side-effects when adding the property of 'fixed', specifically on iOS devices. Removing that property has improved the usability of that control.
---
- [Frontend](https://nr-compliance-enforcement-572-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-572-frontend.apps.silver.devops.gov.bc.ca/api) …
=> feat: CE-825 - Fix Select Component on iPad

frontend/src/assets/sass/form.scss
Fix an issue where the icon in the date/time picker doesn't respond to press/click events. I've attempted to use the prop as provided by the documentation for this control, however it doesn't seem to function. Alternative solution was to completely negate any pointer events on the SVG so users can directly interact with the input control itself.
---
- [Frontend](https://nr-compliance-enforcement-575-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-575-frontend.apps.silver.devops.gov.bc.ca/api)
Please …
=> feat: CE-751 - Make Calendar Icon Clickable

.github/workflows/merge-release.yml, .github/workflows/scheduled.yml
---
- [Frontend](https://nr-compliance-enforcement-571-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-571-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: SchemaSpy for Database Schema Documentation

frontend/src/app/store/migrations.ts, frontend/src/app/store/migrations/migration-10.ts, frontend/src/app/store/migrations/migration-11.ts
---
- [Frontend](https://nr-compliance-enforcement-579-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-579-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: code table store

migrations/migrations/R__Create-Test-Data.sql, migrations/migrations/V0.25.0__CE-995.sql
Added team and officer_team_xref tables (as well as the history tables).
Added DML scripts to populate team table.
---
- [Frontend](https://nr-compliance-enforcement-584-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-584-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> feat: CE-995 Teams data model changes

frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/drug-used.tsx
Fixes the text so it only displays 'Add drug' in the relevant edit screen.
Updated the animal in a few HWCRs and added some drugs to the records, confirmed the text only displays 'Add drug' in these scenarios.
---
- [Frontend](https://nr-compliance-enforcement-588-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-588-frontend.apps.silver.devops.gov.bc.ca/api)
Please create PRs in draft …
=> fix: CE-974

frontend/src/app/components/containers/complaints/outcomes/outcome-attachments.tsx
---
- [Frontend](https://nr-compliance-enforcement-608-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-608-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: CE-1004 add plus icon to button

frontend/src/app/components/containers/complaints/outcomes/outcome-attachments.tsx
---
- [Frontend](https://nr-compliance-enforcement-609-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-609-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: CE-1004-fix-attachment-text-casing

frontend/src/app/components/containers/complaints/complaint-list.tsx, frontend/src/app/components/containers/complaints/headers/allegation-complaint-list-header.tsx, frontend/src/app/components/containers/complaints/headers/general-complaint-list-header.tsx, frontend/src/app/components/containers/complaints/headers/wildlife-complaint-list-header.tsx, frontend/src/app/components/containers/complaints/list-items/allegation-complaint-list-item.tsx, frontend/src/app/components/containers/complaints/list-items/general-complaint-list-item.tsx, frontend/src/app/components/containers/complaints/list-items/wildlife-complaint-list-item.tsx, frontend/src/assets/sass/complaint.scss, frontend/src/assets/sass/layout.scss, frontend/src/assets/sass/mixins.scss
---
- [Frontend](https://nr-compliance-enforcement-614-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-614-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> feat: CE-1029 - UI Updates to Complaints Tables

backend/src/v1/case_file/case_file.controller.ts, frontend/src/app/components/containers/complaints/outcomes/ceeb/ceeb-outcome-report.tsx, frontend/src/app/components/containers/complaints/outcomes/hwcr-outcome-report.tsx, frontend/src/app/components/containers/complaints/outcomes/supplemental-note.tsx, frontend/src/app/components/containers/complaints/outcomes/supplemental-notes/supplemental-notes-input.tsx, frontend/src/app/store/reducers/case-thunks.ts
---
- [Frontend](https://nr-compliance-enforcement-621-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-621-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> feat: CE-1003 Add notes to CEEB complaint outcome

frontend/src/app/components/containers/complaints/list-items/wildlife-complaint-list-item.tsx, frontend/src/assets/sass/complaint.scss
Used the 'old' btn layout CSS in order to create a new 'comp-species-badge' that reflects how it used to look.
---
- [Frontend](https://nr-compliance-enforcement-624-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-624-frontend.apps.silver.devops.gov.bc.ca/api)
- [Analysis …
=> fix: CE 1052 Reapply the button styling for Species

frontend/src/app/components/common/comp-input.tsx, frontend/src/app/components/containers/complaints/outcomes/ceeb/authorization-outcome/authorization-outcome-form.tsx, frontend/src/app/components/containers/complaints/outcomes/ceeb/authorization-outcome/authorization-outcome.tsx, frontend/src/assets/sass/layout.scss
Fixes CE-1073
---
- [Frontend](https://nr-compliance-enforcement-628-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-628-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: CE-1073 and CE-1074 Proper Focus and Validation for Input Groups with bonus typo fixes

frontend/src/assets/sass/layout.scss
---
- [Frontend](https://nr-compliance-enforcement-631-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-631-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: CE-1073: Delay UA transition out effect

frontend/src/app/components/containers/complaints/complaints.tsx
---
- [Frontend](https://nr-compliance-enforcement-643-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-643-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: CE-1056 default filters not showing

.github/workflows/pr-open.yml
No longer deletes old images - temporary change until we have a permanent fix that preserves images tagged with prod or test.
---
- [Frontend](https://nr-compliance-enforcement-644-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-644-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: Image Deletion Issue in Update pr-open.yml

.github/workflows/merge-hotfix.yml, migrations/migrations/R__update-insert-complaint-from-staging.sql
Patch to correctly bring actions taken into the application.
---
- [Frontend](https://nr-compliance-enforcement-651-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-651-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement/actions/workflows/me …
=> fix: CE-1086-Actions Taken not being loaded into system

frontend/src/app/store/reducers/officer.ts, migrations/migrations/R__Create-Test-Data.sql
Adds CEEB Users into the database
---
- [Frontend](https://nr-compliance-enforcement-655-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-655-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore: CE-951 CEEB user data load

frontend/src/app/components/containers/complaints/outcomes/ceeb/ceeb-decision/decision-form.tsx
removed required field validation on the NRIS inspection number, and added format and length validation 
Story # CE-1067
---
- [Frontend](https://nr-compliance-enforcement-658-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-658-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> feat: CE-1067 NRIS number data validation

frontend/src/app/components/containers/complaints/outcomes/ceeb/ceeb-decision/decision-form.tsx
Reverts bcgov/nr-compliance-enforcement#658
---
- [Frontend](https://nr-compliance-enforcement-660-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-660-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: Revert "feat: CE-1067 NRIS number data validation"

.github/workflows/pr-version-bump.yml
=> feat: Update pr-version-bump.yml

.github/workflows/pr-version-bump.yml
=> Ce 882 test

.github/workflows/pr-version-bump.yml
=> feat: CE-882 test

frontend/src/app/store/reducers/complaints.ts
Fix incorrect value displayed in the tab in map view (both COS and CEEB)
---
- [Frontend](https://nr-compliance-enforcement-682-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-682-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement/actions/ …
=> fix: CE-897 incorrect value in tab map view

frontend/index.html
No change here aside from removing a period from an unused file.  Done to trigger a PR workflow.
---
- [Frontend](https://nr-compliance-enforcement-687-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-687-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: Pipeline fix

migrations/migrations/R__Create-Test-Data.sql, migrations/test-only-migrations/R__Test-Data-Creation.sql
Adds Ryan as user & officer to test/prod data per https://env-ceds.atlassian.net/browse/CE-1116
---
- [Frontend](https://nr-compliance-enforcement-689-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-689-frontend.apps.silver.devops.gov.bc.ca/api)
---
- [Frontend](https://nr-compliance-enforcement-689-frontend.apps.silv …
=> chore(CE-1118): CE-1118 Add Ryan as officer for test and prod

migrations/migrations/R__Create-Test-Data.sql, migrations/test-only-migrations/R__Test-Data-Creation.sql
Adds Mike as a person and officer in the test data creation scripts.
CE-1119
Assigned myself the COS Officer role in Dev/Test/Prod in CSS, and the READ_ONLY role in prod.
---
- [Frontend](https://nr-compliance-enforcement-690-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-690-frontend.apps.silver.devops.gov.bc.ca/api)
- …
=> chore: CE 1119 add Mike to users

frontend/index.html
---
- [Frontend](https://nr-compliance-enforcement-717-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-717-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: prod deployment

backend/src/external_api/case_management.ts, backend/src/types/models/case-files/wildlife/drug-used-input.ts, backend/src/types/models/case-files/wildlife/wildlife-input.ts, frontend/src/app/components/containers/complaints/outcomes/hwcr-outcome-by-animal-v2.tsx, frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/animal-outcome.tsx, frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/create-outcome.tsx, frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/drug-item.tsx, frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/drug-used.tsx, frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/edit-outcome.tsx, frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/outcome-common.ts, frontend/src/app/store/migrations.ts, frontend/src/app/store/migrations/migration-20.ts, frontend/src/app/store/reducers/case-selectors.ts, frontend/src/app/store/reducers/case-thunks.ts, frontend/src/app/store/store.ts, frontend/src/app/types/app/case-files/animal-outcome/animal-outcome-input.ts, frontend/src/app/types/app/case-files/animal-outcome/drug-used-input.ts, frontend/src/app/types/app/complaints/outcomes/wildlife/animal-outcome.ts, frontend/src/app/types/app/complaints/outcomes/wildlife/drug-used.ts, frontend/src/app/types/state/cases-state.ts
Addresses [CE-556](https://env-ceds.atlassian.net/browse/CE-556). Changes to some fields and available options when entering Drug information for animals. 
**Note**: This PR is paired with an [equivalent PR in Case Management](https://github.com/bcgov/nr-compliance-enforcement-cm/pull/101).
- Added _Oral/nasal_ to options in 'Injection method'.
- Replaced an option in 'Fate of remaining...' with _Returned to vet_. 
- Removed _Adverse reactions_, _Discard method_, and _Amount discarded_ fields.
- Added _Additional comments_ text field.
- (In CM DB) Migrated removed fields' data into _Additional comments_ data. 
0. Ensure both this and `...cm` repo are on this issue's branch.
1. Run a local instance of the application, log in. 
2. Navigate to a HWC complaint and **Add animal**, then **Add …
=> chore: CE-556 HWCR drug administration information updates

frontend/src/app/components/containers/complaints/outcomes/hwcr-complaint-assessment.tsx, frontend/src/app/components/modal/instances/quick-close-modal.tsx
https://env-ceds.atlassian.net/browse/CE-1249
https://env-ceds.atlassian.net/browse/CE-1250
---
- [Frontend](https://nr-compliance-enforcement-750-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-750-frontend.apps.silver.devops.gov.bc.ca/api)
---
- [Frontend](https://nr-compliance-enforcement-750-frontend.apps.silver.d …
=> fix: CE-1249, CE-1250 QC Modal Validation Bug

.github/workflows/merge-release.yml, .github/workflows/release-main.yml
---
- [Frontend](https://nr-compliance-enforcement-762-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-762-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: backup size

charts/app/templates/frontend/templates/deployment.yaml
bringing in changes made to QSOS for fixing caddy errors,
https://github.com/bcgov/quickstart-openshift/pull/2177
---
- [Frontend](https://nr-compliance-enforcement-769-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-769-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: caddy errors

exports/cos_hwcr_complaint_export.sql, exports/cos_hwcr_export.sql
Adds export queries to version control instead of keeping them in teams.
---
- [Frontend](https://nr-compliance-enforcement-774-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-774-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement/actions/ …
=> chore: add exports

frontend/src/app/store/migrations.ts, frontend/src/app/store/migrations/migration-23.ts
Refresh assessment type code table values in redux store.
Changes were made to the code table values for animal actions, so the assessment_type list has been refreshed in a Redux migrations. 
Fixes # https://env-ceds.atlassian.net/jira/software/c/projects/CE/boards/4?selectedIssue=CE-1288
---
- [Frontend](https://nr-compliance-enforcement-782-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-782-frontend.apps.silver.devops.gov.bc.ca/api)
- [Analysis …
=> chore: CE-1288 animal action updates

frontend/src/app/store/migrations.ts, frontend/src/app/store/migrations/migration-23.ts
---
- [Frontend](https://nr-compliance-enforcement-788-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-788-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore: cherry pick 1288

.github/workflows/release-main.yml
- uses ns from vars
---
- [Frontend](https://nr-compliance-enforcement-805-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-805-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: use namespace from vars in deploy

.github/workflows/pr-close.yml, .github/workflows/release-main.yml
Small revisions for envar consistency.
---
- [Frontend](https://nr-compliance-enforcement-807-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-807-frontend.apps.silver.devops.gov.bc.ca/api)
=> ci: secret/var consistency

charts/app/values.yaml
---
- [Frontend](https://nr-compliance-enforcement-810-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-810-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: metabase connection

.github/workflows/release-main.yml
---
- [Frontend](https://nr-compliance-enforcement-813-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-813-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: remove pvc template change in prod pipeline

charts/app/templates/backend/templates/deployment.yaml
---
- [Frontend](https://nr-compliance-enforcement-815-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-815-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore: Adjust cpu requets for backend

charts/app/templates/backend/templates/deployment.yaml, frontend/package-lock.json
---
- [Frontend](https://nr-compliance-enforcement-816-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-816-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore: Fixes npm audit issues in package-lock.json

.github/workflows/pr-close.yml, .github/workflows/release-main.yml
---
- [Frontend](https://nr-compliance-enforcement-821-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-821-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore: update 0.6.9 main

frontend/src/app/components/containers/zone-at-a-glance/zone-at-a-glance.tsx
Zone at a glance page: fix Enforcement pie chart for not showing correct statistics
---
- [Frontend](https://nr-compliance-enforcement-819-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-819-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: CE-1291 zone at a glance-enforcement not correct

backend/src/v1/complaint/complaint.service.ts, frontend/src/app/components/containers/complaints/complaint-list.tsx
---
- [Frontend](https://nr-compliance-enforcement-836-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-836-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: CE-1328 Pagination Fix

frontend/src/app/components/mapping/leaflet-map-with-server-side-clustering.tsx, frontend/src/app/components/mapping/spiderfy.tsx
---
- [Frontend](https://nr-compliance-enforcement-851-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-851-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: Clear Event Listeners On Unmount

backend/src/app.controller.spec.ts, backend/src/app.controller.ts, backend/src/app.service.ts
https://env-ceds.atlassian.net/browse/CE-1300
Tested by manually calling the /api/ endpoint and verifying "Success" message, then stopping the DB container and verifying 503 error is returned.
---
- [Frontend](https://nr-compliance-enforcement-854-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-854-frontend.apps.silver.devops.gov.bc.ca/api)
---
Deployments, as …
=> chore: CM-1300 Test DB Connection In Health Check

.github/workflows/merge-release.yml, .github/workflows/release-main.yml
Adds passing of s3 config to pgbackrest for crunchy
---
- [Frontend](https://nr-compliance-enforcement-867-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-867-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: passin s3 config to pgbackrest

.github/workflows/.dbdeployer.yml, .github/workflows/merge-release.yml, .github/workflows/release-main.yml, charts/crunchy/values.yaml
---
- [Frontend](https://nr-compliance-enforcement-869-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-869-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: crunchy s3 missing

charts/app/templates/backend/templates/deployment.yaml
---
- [Frontend](https://nr-compliance-enforcement-870-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-870-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: backend template with crunchy

.github/workflows/merge-release.yml
---
- [Frontend](https://nr-compliance-enforcement-871-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-871-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore: enable crunchy in test

.github/workflows/merge-release.yml, .github/workflows/release-main.yml
---
- [Frontend](https://nr-compliance-enforcement-872-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-872-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: crunchy value keys

charts/app/templates/backend/templates/deployment.yaml
---
- [Frontend](https://nr-compliance-enforcement-873-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-873-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: direct connect with crunchy

backend/src/auth/decorators/roles.decorator.ts, backend/src/enum/role.enum.ts, backend/src/external_api/bc_geo_coder/bc_geo_coder.controller.ts, backend/src/v1/case_file/case_file.controller.ts, backend/src/v1/code-table/code-table.controller.ts, backend/src/v1/comp_mthd_recv_cd_agcy_cd_xref/comp_mthd_recv_cd_agcy_cd_xref.controller.ts, backend/src/v1/complaint/complaint.controller.ts, backend/src/v1/complaint_updates/complaint_updates.controller.ts, backend/src/v1/configuration/configuration.controller.ts, backend/src/v1/document/document.controller.ts, backend/src/v1/feature_flag/feature_flag.controller.ts, backend/src/v1/office/office.controller.ts, backend/src/v1/officer/officer.controller.ts, backend/src/v1/person/person.controller.ts, backend/src/v1/person_complaint_xref/person_complaint_xref.controller.ts, frontend/src/app/App.tsx, frontend/src/app/constants/ceeb-roles.ts, frontend/src/app/store/reducers/officer.ts, frontend/src/app/types/app/complaint-types.ts, frontend/src/app/types/app/roles.ts
Change the base role for COS from "COS Officer" to "COS". 
Since not all COS users will be officers, COS Officer is no longer used as the base role assigned to all users in the COS. The COS Officer role still exists, and a new "COS" role was added to be used as the base role for the agency. Any existing users in the system with the COS Officer role will need to had COS added to their role set.
Accompanying CM PR: https://github.com/bcgov/nr-compliance-enforcement-cm/pull/117
Fixes # CE-1347
https://env-ceds.atlassian.net/jira/software/c/projects/CE/boards/4?selectedIssue=CE-1347
- Assigned myself the COS role and removed …
=> chore: CE-1347 replace COS Officer with COS role

.github/workflows/release-main.yml
---
- [Frontend](https://nr-compliance-enforcement-875-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-875-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore: enable prod crunchy

frontend/src/app/components/containers/complaints/details/complaint-details-create.tsx, frontend/src/assets/sass/complaint.scss
Fixes missed color and sentence case change for 1345 / 1377
---
- [Frontend](https://nr-compliance-enforcement-890-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-890-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: address 1345/1377 QA changes

backend/src/v1/complaint/complaint.service.ts
Fixes # CE-1397
---
- [Frontend](https://nr-compliance-enforcement-892-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-892-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: Unable to export complaint with N/A last updated date

migrations/migrations/R__Create-Test-Data.sql
---
- [Frontend](https://nr-compliance-enforcement-896-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-896-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: CE-1360 fix for truncated webEOC values

backend/src/v1/code-table/code-table.service.spec.ts, backend/test/mocks/mock-code-table-repositories.ts, migrations/migrations/R__Create-Test-Data.sql, migrations/test-only-migrations/R__Test-Data-Creation.sql
---
- [Frontend](https://nr-compliance-enforcement-898-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-898-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore: Update 1.0.2 with final 1.0.1 changes

.github/workflows/.dbdeployer.yml, .github/workflows/analysis.yml, .github/workflows/pr-open.yml, .github/workflows/pr-version-bump.yml
---
- [Frontend](https://nr-compliance-enforcement-909-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-909-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore(ci): remove JS handling from workflow conditionals

frontend/cypress/e2e/complaint-filter-cascade.cy.ts, frontend/src/app/store/reducers/code-table.ts, migrations/migrations/R__Create-Test-Data.sql, migrations/migrations/R__staging-metadata-mapping.sql
- Add new community 'Field' to the Golden Office
- Move community 'Houston' to the Smithers Office
- Fix a bug where the community cache isn't refreshed when the version number changes
Fixes # 
CE-1403
CE-1410
---
- [Frontend](https://nr-compliance-enforcement-907-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-907-frontend.apps.silver.devops.gov.bc.ca/api)
Please create PRs in draft mode.  Mark as …
=> feat: webEOC Community Changes

charts/crunchy/templates/PostgresCluster.yaml, charts/crunchy/values.yaml, database/openshift.deploy.yml
- Remove CPU and Memory Limits from Crunchy values file
- Also cleaned up some limit related values in other files
Fixes # CE-1373
---
- [Frontend](https://nr-compliance-enforcement-911-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-911-frontend.apps.silver.devops.gov.bc.ca/api)
- [Analysis …
=> chore: Remove crunchy limits

backend/src/v1/officer/officer.controller.ts
Fixes adding new users with the CEEB and TEMPORARY_TEST_ADMIN  roles https://env-ceds.atlassian.net/browse/CE-1417
---
- [Frontend](https://nr-compliance-enforcement-923-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-923-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: CE-1417

frontend/src/app/store/reducers/case-thunks.ts
Fixes https://env-ceds.atlassian.net/browse/CE-1431
---
- [Frontend](https://nr-compliance-enforcement-926-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-926-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: CE-1431 fix ear tags error

frontend/src/app/components/containers/complaints/outcomes/hwcr-equipment/equipment-form.tsx
fixes: https://env-ceds.atlassian.net/browse/CE-1436
---
- [Frontend](https://nr-compliance-enforcement-927-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-927-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: CE-1436 Equipment Quantity Numeric Validation

charts/app/templates/frontend/templates/deployment.yaml, charts/app/values.yaml
---
- [Frontend](https://nr-compliance-enforcement-929-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-929-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: frontend issues around startup and session

terraform/alerts_prod.tf, terraform/alerts_test.tf
Setup Sysdig alerts for Crunchy
The Sysdig alerts have been switched from monitoring the old Bitnami postgres stateful set to monitoring the Crunchy DB stateful sets. Since Bitnami was a single stateful set but Crunchy is multiple, the selector in the query has been changed to be label based rather than name based.
The threshold for the storage alert was also changed from 70% to 65% to provide us with a little more time (the current version of crunchy that we are using gets problematic at 75%).
---
- …
=> chore: Target crunchy for sysdig alerts instead of bitnami

migrations/migrations/R__reset-templates.sql
---
- [Frontend](https://nr-compliance-enforcement-934-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-934-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: CE-1438 actions update is not shown in GIR export

frontend/src/app/components/containers/complaints/webeoc-complaint-updates/webeoc-complaint-update-list.tsx, frontend/src/assets/sass/complaint.scss
Change UI of green updates banners to match with design: https://www.figma.com/design/0cfmNnWi31hBSKqMSp5OXf/CEDS-%E2%80%93-Designs
---
- [Frontend](https://nr-compliance-enforcement-940-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-940-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> feat: CE-1334 update banner UI

backend/src/v1/complaint/complaint.controller.ts, backend/src/v1/complaint/complaint.service.ts, frontend/cypress/e2e/general-incident-details-create.cy.ts, frontend/src/app/components/containers/complaints/details/complaint-details-create.tsx, frontend/src/app/store/reducers/code-table.ts, frontend/src/app/store/reducers/complaints.ts, migrations/migrations/R__Create-Test-Data.sql, migrations/migrations/R__staging-metadata-mapping.sql
This PR is to allow users to create General Incident Reports via NatCom
Fixes # (CE-1370)
---
- [Frontend](https://nr-compliance-enforcement-938-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-938-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement/actions …
=> feat: CE-1370-Create-GIRs-through-NatCom

.sonarcloud.properties, exports/cos_hwcr_complaint_export.sql, exports/ers_hwcr_complaint_export.sql
- Split HWCR and ERS updates
- Add COORS Number
- Better (not great) management of PDT/PST
- Include Update times
- Display original species when species was changed 
---
- [Frontend](https://nr-compliance-enforcement-937-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-937-frontend.apps.silver.devops.gov.bc.ca/api)
- [Analysis …
=> feat: Export updates

frontend/src/app/store/reducers/code-table.ts
fixes https://env-ceds.atlassian.net/browse/CE-1451
To reproduce, set yourself to CEEB User role only combined with the test admin role, then follow the instructions in the ticket to edit  your user roles.
---
- [Frontend](https://nr-compliance-enforcement-946-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-946-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: CE-1451

frontend/src/app/common/validation-checkbox-group.tsx
---
- [Frontend](https://nr-compliance-enforcement-950-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-950-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: Infinite Rerender

frontend/src/app/components/containers/complaints/list-items/complaint-action-items.tsx, frontend/src/app/store/reducers/officer.ts
- Quick Close option is disabled for closed complaints in the list view
- Removed condition that stated a COS Officer had to be assigned to an office to appear in the Officer searches / drop downs
Fixes # 
CE-1465
CE-1440
---
- [Frontend](https://nr-compliance-enforcement-952-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-952-frontend.apps.silver.devops.gov.bc.ca/api)
Please create PRs in draft …
=> fix: CE-1465 and CE-1440 bug fixes

.github/scripts/rollout_healthcheck.sh
Update selector in healthcheck to only get Running and Pending pods.
The health check was failing due to Succeded and Failed pods not being filtered out. This change filters them out along with pods in the Unknown status out of the `oc get`.
Fixes # CE-1310
https://env-ceds.atlassian.net/jira/software/c/projects/CE/boards/4?selectedIssue=CE-1310
---
- [Frontend](https://nr-compliance-enforcement-959-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-959-frontend.apps.silver.devops.gov.bc.ca/api)
Please create PRs in …
=> chore: CE-1310 Filter pods by status in healthcheck

frontend/cypress/e2e/ceeb-user-complaint-decision.cy.ts, frontend/src/app/components/containers/complaints/outcomes/ceeb/authorization-outcome/authorization-outcome-form.tsx, frontend/src/app/components/containers/complaints/outcomes/ceeb/authorization-outcome/authorization-outcome-item.tsx, frontend/src/app/components/containers/complaints/outcomes/ceeb/ceeb-decision/decision-item.tsx
This PR adds a set of tests that test creating, editing, and saving authorization and decisions on CEEB complaints. As part of this it validates the business rules added as a part of CE-1084 https://env-ceds.atlassian.net/browse/CE-1084
---
- [Frontend](https://nr-compliance-enforcement-965-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-965-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore: CE-1482 add new tests for ceeb complaints

frontend/src/assets/sass/misc.scss
Correct the colour of the search button.
---
- [Frontend](https://nr-compliance-enforcement-964-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-964-frontend.apps.silver.devops.gov.bc.ca/api)
After merge, new images are …
=> chore: CE-1491 Change colour of search button

frontend/cypress/e2e/ceeb-user-complaint-decision.cy.ts, frontend/cypress/e2e/hwcr-outcome-equipment.cy.ts, frontend/src/app/components/containers/complaints/outcomes/ceeb/authorization-outcome/authorization-outcome.tsx, webeoc/src/webeoc-scheduler/webeoc-scheduler.service.ts
Two major changes:
- Only authenticate once for each 'series' of webEOC API calls
- Logout afterwards
Fixes # CE-1478
---
- [Frontend](https://nr-compliance-enforcement-968-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-968-frontend.apps.silver.devops.gov.bc.ca/api)
- [Analysis Workflow](https://github.com/bcgov/nr-compliance-enforcement/acti …
=> feat: Improve webEOC Session Handling

frontend/src/app/components/containers/complaints/webeoc-complaint-updates/webeoc-complaint-update-list.tsx
Fixes # CE-1543
---
- [Frontend](https://nr-compliance-enforcement-969-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-969-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: Add Phone Number formatting to Update banners

backend/src/v1/complaint/complaint.service.ts
Fixes # CE-1543
---
- [Frontend](https://nr-compliance-enforcement-971-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-971-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: format phone numbers for exports

backend/src/common/methods.ts
---
- [Frontend](https://nr-compliance-enforcement-973-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-973-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: Add Null Check to format Phone Number method

.github/workflows/pr-version-bump.yml
Testing action by merging this into feature branch rather than release.
Updated the variable name and secret name to match what is showing in Settings.
Also added an checker to the workflow while debugging to see if the issue is with the action being called or the reference itself.
---
- [Frontend](https://nr-compliance-enforcement-975-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-975-frontend.apps.silver.devops.gov.bc.ca/api)
- [Analysis …
=> chore: Fix and check for valid vars and secrets

.github/workflows/pr-version-bump.yml
---
- [Frontend](https://nr-compliance-enforcement-976-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-976-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore: Ce 1476 remove if to allow variable check

.github/workflows/pr-version-bump.yml
=> chore:  type fix

.github/workflows/pr-version-bump.yml
=> Better handle the decoding of the secret

.github/workflows/pr-version-bump.yml
=> Move delete tag to end of commands

.github/workflows/pr-version-bump.yml, .github/workflows/release-branch-creation.yml, backend/package.json, frontend/package.json, webeoc/package.json
Fix version bump action to properly use Github app
This update fixes the use the GitHub app in the version bumping workflows. The referencing was corrected, and the app private key is now decoded and safely passed to the token fetching action. This has been applied to the `pr-version-bump.yml` and `release-branch-creation.yml`, however the release action was left untouched.
The target branch of the actions was temporarily set to this branch, and changes were merged into this branch to run the action without disturbing `release/1.5`.
---
- [Frontend](https://nr-compliance-enforcement-974-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-974-frontend.apps.silver.devops.gov …
=> chore: Fix vars and secrets in version bumper

frontend/src/app/components/containers/complaints/details/complaint-header.tsx
Fixes # (issue) CE-1562
---
- [Frontend](https://nr-compliance-enforcement-984-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-984-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> feat:  Only allow referrals of open complaints

frontend/cypress/e2e/complaint-filter-cascade.cy.ts, migrations/migrations/R__Create-Test-Data.sql, migrations/migrations/V0.40.0__CE-1561.sql
Fixes # CE-1561
---
- [Frontend](https://nr-compliance-enforcement-986-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-986-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore: Update Cluculz Lake Communities

migrations/migrations/V0.40.0__CE-1561.sql
---
- [Frontend](https://nr-compliance-enforcement-988-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-988-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: Broken flyway script - materialized view already exists in test and prod

migrations/migrations/R__Create-Test-Data.sql
Added comment to SQL script to force flyway to rerun the script in test.
---
- [Frontend](https://nr-compliance-enforcement-991-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-991-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore: CE-1561 Trigger Rerunnable

frontend/cypress/e2e/ceeb-user-complaint-method.cy.ts, frontend/src/app/components/containers/complaints/details/complaint-header.tsx, frontend/src/app/store/reducers/complaints.ts
---
- [Frontend](https://nr-compliance-enforcement-990-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-990-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> feat: CE-1475 Prevent user from editing complaint after referral

backend/src/v1/complaint/complaint.service.ts, backend/src/v1/complaint/entities/complaint.entity.ts, backend/src/v1/complaint_referral/entities/complaint_referral.entity.ts, frontend/src/app/common/methods.tsx, frontend/src/app/components/containers/complaints/complaint-filter.tsx, frontend/src/app/components/containers/complaints/details/complaint-header.tsx, frontend/src/app/components/containers/complaints/list-items/allegation-complaint-list-item.tsx, frontend/src/app/components/containers/complaints/list-items/complaint-action-items.tsx, frontend/src/app/components/containers/complaints/list-items/general-complaint-list-item.tsx, frontend/src/app/components/containers/complaints/list-items/wildlife-complaint-list-item.tsx, frontend/src/app/components/mapping/complaint-summary-popup.tsx, frontend/src/app/store/reducers/complaints.ts, frontend/src/app/types/complaints/details/complaint-details.ts
Returns search results that include complaints that were referred by the agency and adds a derived status of Referred in the frontend.
https://env-ceds.atlassian.net/browse/CE-1453
---
- [Frontend](https://nr-compliance-enforcement-993-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-993-frontend.apps.silver.devops.gov.bc.ca/api)
=> feat: CE-1453

charts/app/templates/secret.yaml, frontend/cypress.config.ts, frontend/public/index.html, frontend/public/static/js/custom-script.js
nt
---
- [Frontend](https://nr-compliance-enforcement-994-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-994-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore: BC Parks API Secrets

frontend/src/app/components/mapping/leaflet-map-with-point.tsx, frontend/src/app/components/mapping/leaflet-map-with-server-side-clustering.tsx
Adds a BC Parks layer to the map views.
---
- [Frontend](https://nr-compliance-enforcement-996-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-996-frontend.apps.silver.devops.gov.bc.ca/api)
=> feat: CE-1474

frontend/cypress/e2e/change-complaint-status-details-view.cy.ts, frontend/src/app/components/containers/complaints/outcomes/external-file-reference.tsx
Updated message indicating that entering a COORS number will close the complaint.
A request was made for a tweak in the wording of this message.
Included  in this PR was a fix to a cypress test related to the status changes implemented in the other CE-1500 PR.
---
- [Frontend](https://nr-compliance-enforcement-998-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-998-frontend.apps.silver.devops.gov.bc.ca/api)
- [Analysis …
=> chore: Update wording of COORS message

backend/src/v1/complaint/complaint.service.ts
fixes: https://env-ceds.atlassian.net/browse/CE-1571
---
- [Frontend](https://nr-compliance-enforcement-997-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-997-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: CE-1571

migrations/migrations/R__update_log_complaint_update.sql
Differentiate between new updates and edits to existing updates.
New updates to complaints with an existing update were using the previous updates values for fields that the new update did not change, as if the new update were an edit to the previous update. This addresses that by explicitly checking if the update seq. number has been seen before.
---
- [Frontend](https://nr-compliance-enforcement-995-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-995-frontend.apps.silver.devops.gov.bc.ca/api) …
=> chore: Only use previous update values on update edits

migrations/migrations/R__staging-metadata-mapping.sql
Fixes # CE-1578
---
- [Frontend](https://nr-compliance-enforcement-1000-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1000-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore: Fix webEOC spelling error on Mount Robson

.github/actions/get-gh-app-token/action.yml, .github/workflows/pr-version-bump.yml
---
- [Frontend](https://nr-compliance-enforcement-1004-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1004-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore: Move checkout to workflow

.github/actions/get-gh-app-token/action.yml
=> chore: Set app slug output

.github/workflows/pr-version-bump.yml
---
- [Frontend](https://nr-compliance-enforcement-1007-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1007-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore: Uncomment code pushing version changes, add Helm change

.github/workflows/pr-version-bump.yml
=> chore: Git add the chart as well

.github/workflows/pr-version-bump.yml, .github/workflows/release-branch-creation.yml
=> Chore: add helm to version push

.github/workflows/pr-version-bump.yml
Move the version bumping workflow trigger to be comment based.
Run the workflow on a PR by commenting /patch_version
---
- [Frontend](https://nr-compliance-enforcement-1010-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1010-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore: Trigger version with /patch_version comment

frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx, frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/animal-outcome.tsx, frontend/src/assets/sass/complaint.scss, frontend/src/assets/sass/outcome-report.scss
---
- [Frontend](https://nr-compliance-enforcement-1001-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1001-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: Remove margin from complaint edit button

.github/workflows/pr-version-bump.yml, .github/workflows/release-branch-creation.yml, backend/package.json, charts/app/Chart.yaml, frontend/package.json, webeoc/package.json
---
- [Frontend](https://nr-compliance-enforcement-1006-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1006-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore: Comment trigger for patch version updates 

backend/dataloader/bulk-data-loader.js, backend/package.json, backend/src/v1/gir_type_code/entities/gir_type_code.entity.ts, backend/test/mocks/mock-code-table-repositories.ts, charts/app/Chart.yaml, frontend/package.json, migrations/migrations/R__Create-Test-Data.sql, migrations/migrations/R__staging-metadata-mapping.sql, webeoc/package.json
---
- [Frontend](https://nr-compliance-enforcement-1017-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1017-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore: CE-1577 Change GIR type code

backend/package.json, charts/app/Chart.yaml, frontend/package.json, frontend/src/app/components/common/park.tsx, frontend/src/assets/sass/complaint.scss, webeoc/package.json
---
- [Frontend](https://nr-compliance-enforcement-1022-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1022-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: Park Filter styles

backend/package.json, charts/app/Chart.yaml, frontend/package.json, frontend/src/app/components/containers/complaints/details/complaint-header.tsx, frontend/src/app/components/modal/instances/manage-collaborators-modal.tsx, frontend/src/assets/sass/misc.scss, migrations/migrations/V0.41.3__CE-1610-assign-CEEB-agency.sql, migrations/test-only-migrations/R__Test-Data-Creation.sql, webeoc/package.json
Update initial agency assignment of officers and collaborator styles.
Updated the initial agency assignment to assign users with no office to EPO.
Addressed minor style changes including order of name in tooltip and modal.
---
- [Frontend](https://nr-compliance-enforcement-1027-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1027-frontend.apps.silver.devops.gov.bc.ca/api)
- [Analysis …
=> feat: CE-1610 Update collaborator styling and agency assignment

backend/package.json, charts/app/Chart.yaml, frontend/package.json, frontend/src/app/components/containers/complaints/details/complaint-header.tsx, webeoc/package.json
Remove period after name in tooltip
---
- [Frontend](https://nr-compliance-enforcement-1028-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1028-frontend.apps.silver.devops.gov.bc.ca/api)
After merge, new images are …
=> chore: CE-1610 remove period after name in tooltip

backend/package.json, backend/src/types/models/code-tables/prevention-type.ts, backend/src/v1/code-table/code-table.service.ts, charts/app/Chart.yaml, frontend/package.json, frontend/src/app/components/containers/complaints/outcomes/hwcr-prevention-education.tsx, frontend/src/app/store/reducers/case-thunks.ts, frontend/src/app/store/reducers/code-table.ts, frontend/src/app/types/app/code-tables/prevention-type.ts, webeoc/package.json
- Adds agency specific Prevention and Education options for Parks users.   
Note: Case Management Changes are required for this PR
Fixes # CE-1574
---
- [Frontend](https://nr-compliance-enforcement-1031-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1031-frontend.apps.silver.devops.gov.bc.ca/api)
- [Analysis …
=> feat: Parks specific options for  Prevention and Education

backend/package.json, charts/app/Chart.yaml, frontend/package.json, tools/gitops/README.md, tools/gitops/argo-app-of-apps.yaml, tools/gitops/gitops-team.yaml, webeoc/package.json
- adds docs and setup steps for argocd pipeline with natcom
---
- [Frontend](https://nr-compliance-enforcement-1034-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1034-frontend.apps.silver.devops.gov.bc.ca/api)
=> feat: argocd setup

backend/package.json, charts/app/Chart.yaml, frontend/package.json, frontend/src/app/store/reducers/code-table.ts, migrations/migrations/R__Create-Test-Data.sql, webeoc/package.json
Fixes # CE-1608
---
- [Frontend](https://nr-compliance-enforcement-1035-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1035-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> feat: Add EPD Team

backend/package.json, charts/app/Chart.yaml, frontend/package.json, frontend/src/app/components/containers/complaints/outcomes/hwcr-outcome-report.tsx, webeoc/package.json
Fixes # CE-1605
---
- [Frontend](https://nr-compliance-enforcement-1043-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1043-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: clear case from redux when outcome unmounts

frontend/src/app/store/migrations.ts
Add the migration for the actioned by codes to the migrations list.
Added the migration to the list so that it will apply for users when released.
---
- [Frontend](https://nr-compliance-enforcement-1050-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1050-frontend.apps.silver.devops.gov.bc.ca/api)
- …
=> chore: CE-1573 Add migration to list

backend/package.json, charts/app/Chart.yaml, frontend/package.json, frontend/src/app/components/containers/complaints/outcomes/hwcr-equipment/equipment-form.tsx, webeoc/package.json
---
- [Frontend](https://nr-compliance-enforcement-1051-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1051-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: Crash on equip screen with assignee+collab

backend/package.json, charts/app/Chart.yaml, frontend/package.json, frontend/src/app/components/containers/complaints/complaint-filter-bar.tsx, webeoc/package.json
When clearing the outcome by animal as it no longer applies in that case.
---
- [Frontend](https://nr-compliance-enforcement-1052-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1052-frontend.apps.silver.devops.gov.bc.ca/api)
- [Analysis Workflow](https://github.com/bcgov/nr-compliance-enforcement/actions/workflows/analysis.yml …
=> feat: CE-1645 Clear actioned by filter with animal outcome

backend/package.json, backend/src/types/models/code-tables/index.ts, backend/src/types/models/people/officer.ts, backend/src/v1/code-table/code-table.service.ts, backend/src/v1/officer/dto/create-officer.dto.ts, backend/src/v1/officer/dto/officer.dto.ts, backend/src/v1/officer/entities/officer.entity.ts, backend/src/v1/officer/officer.service.ts, charts/app/Chart.yaml, frontend/package.json, frontend/src/app/components/containers/admin/user-management/edit-user.tsx, frontend/src/app/constants/code-table-types.ts, frontend/src/app/store/migrations.ts, frontend/src/app/store/migrations/migration-30.ts, frontend/src/app/store/migrations/migration-31.ts, frontend/src/app/store/reducers/code-table-selectors.ts, frontend/src/app/store/reducers/code-table-thunks.ts, frontend/src/app/store/reducers/code-table.ts, frontend/src/app/store/store.ts, frontend/src/app/types/app/code-tables/park-area.ts, frontend/src/app/types/person/new-officer.ts, frontend/src/app/types/person/person.ts, frontend/src/app/types/state/code-table-state.ts, migrations/migrations/V0.43.0__CE-1542.sql, webeoc/package.json
---
- [Frontend](https://nr-compliance-enforcement-1058-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1058-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> feat: CE-1542 Add park area to Admin page

backend/package.json, charts/app/Chart.yaml, frontend/package.json, frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx, webeoc/package.json
The edit screen was crashing if an invalid coordinate value was passed to leaflet.   This PR will only attempt to render the marker if the coordinates have passed validation.
Fixes # CE-1634
---
- [Frontend](https://nr-compliance-enforcement-1056-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1056-frontend.apps.silver.devops.gov.bc.ca/api)
- …
=> fix: Error message on edit screen when invalid coordinates entered

.github/workflows/merge-release.yml, .github/workflows/pr-close.yml, .github/workflows/pr-open.yml, backend/package.json, charts/app/Chart.yaml, frontend/package.json, webeoc/package.json
- Enables management of ephemeral crunchy databases for developer environments
- Does not interact with the currently used silver crunchy in anyway, this action just writes a yaml file change to a gitops repo
---
- [Frontend](https://nr-compliance-enforcement-1059-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1059-frontend.apps.silver.devops.gov.bc.ca/api)
- [Analysis Workflow](https://github.com/bcgov/nr-compliance-enforcement/actions/workflows/analysis.ym …
=> feat: crunchy operations for dev env

backend/package.json, charts/app/Chart.yaml, frontend/package.json, frontend/src/app/store/migrations.ts, frontend/src/app/store/migrations/migration-32.ts, webeoc/package.json
Forgot to add a migration
---
- [Frontend](https://nr-compliance-enforcement-1062-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1062-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: CE-1455 Multiple Assessments

backend/package.json, charts/app/Chart.yaml, frontend/package.json, migrations/migrations/R__Create-Test-Data.sql, webeoc/package.json
Added zone shared email address for South Peace.
---
- [Frontend](https://nr-compliance-enforcement-1075-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1075-frontend.apps.silver.devops.gov.bc.ca/api)
After merge, new …
=> chore: Add missing zone shared email

charts/crunchy/templates/PostgresCluster.yaml
Comitted fix for crunchy, this was already manually applied in prod
---
- [Frontend](https://nr-compliance-enforcement-1082-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1082-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement/actions/workflows/merge.yml …
=> fix: crunchy openshift detection

.github/workflows/release-branch-creation.yml, backend/package.json, charts/app/Chart.yaml, frontend/package.json, webeoc/package.json
Fix the naming in the create release branch workflow that was blocking the helm chart update.
Also bumped the major version since this is the first PR into the new release branch.
Fixes # 1596
https://env-ceds.atlassian.net/jira/software/c/projects/CE/boards/4?selectedIssue=CE-1596
Has not been tested, requires making a new release branch so we'll wait to see next sprint.
---
- [Frontend](https://nr-compliance-enforcement-1103-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1103-frontend.apps.silver.devops.gov.bc.ca/api) …
=> chore: CE-1596 fix naming in create release branch

backend/package.json, charts/app/Chart.yaml, frontend/package.json, frontend/src/app/components/common/comp-select.tsx, webeoc/package.json
---
- [Frontend](https://nr-compliance-enforcement-1105-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1105-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: collaborator officers are not searchable

backend/package.json, charts/app/Chart.yaml, frontend/package.json, frontend/src/app/components/modal/instances/refer-complaint-modal.tsx, webeoc/package.json
https://env-ceds.atlassian.net/browse/CE-1715
---
- [Frontend](https://nr-compliance-enforcement-1115-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1115-frontend.apps.silver.devops.gov.bc.ca/api)
=> fix: CE-1715

backend/package.json, charts/app/Chart.yaml, frontend/package.json, frontend/src/app/components/modal/instances/refer-complaint-modal.tsx, frontend/src/app/types/app/complaint-types.ts, webeoc/package.json
https://env-ceds.atlassian.net/browse/CE-1728
---
- [Frontend](https://nr-compliance-enforcement-1120-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1120-frontend.apps.silver.devops.gov.bc.ca/api)
=> feat: CE-1728 HWC Complaints should only be able to be referred between COS and BC Parks

.github/workflows/release-main.yml
---
- [Frontend](https://nr-compliance-enforcement-1123-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1123-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: correct override for backups

backend/package.json, backend/src/v1/email/email.service.ts, charts/app/Chart.yaml, frontend/package.json, webeoc/package.json
Fix null being in email title
Fixes # CE-1737
---
- [Frontend](https://nr-compliance-enforcement-1127-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1127-frontend.apps.silver.devops.gov.bc.ca/api) …
=> feat: Remove null from email title

.github/workflows/.dbdeployer.yml, backend/package.json, charts/app/Chart.yaml, frontend/package.json, webeoc/package.json
---
- [Frontend](https://nr-compliance-enforcement-1141-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1141-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: Dbdeployer fix

.github/scripts/cleanup_scan.sh, backend/Dockerfile, backend/entrypoint.sh
Originally this was a temporary PR but now contains the changes on the app side for the new emerald pipeline - we can merge this or I can make a new branch if needed.
This changes out the runtime image to not be distroless, and this allows us to source vault secrets before handing over to node in the container.
Infra PR https://github.com/bcgov-c/tenant-gitops-f208ae/pull/3
---
- [Frontend](https://nr-compliance-enforcement-1133-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1133-frontend.apps.silver.devops.gov.bc.ca/api) …
=> chore: update backend runtime image

frontend/src/app/components/containers/layout/header.tsx
---
- [Frontend](https://nr-compliance-enforcement-1160-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1160-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> chore: flush pipeline

backend/package.json, charts/app/Chart.yaml, frontend/cypress/e2e/complaint-collaborators.cy.ts, frontend/cypress/e2e/complaint-export.cy.ts, frontend/package.json, frontend/src/app/components/containers/complaints/details/complaint-header.tsx, frontend/src/assets/sass/complaint.scss, webeoc/package.json
---
- [Frontend](https://nr-compliance-enforcement-1161-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1161-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> feat: Updated Action Buttons on Complaint Details Page

tools/terraform/alerts_prod.tf, tools/terraform/alerts_prod_f208ae.tf, tools/terraform/alerts_test.tf, tools/terraform/alerts_test_f208ae.tf
---
- [Frontend](https://nr-compliance-enforcement-1162-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1162-frontend.apps.silver.devops.gov.bc.ca/api)
=> feat: CE-1685 Crunchy Alerts

backend/package.json, charts/app/Chart.yaml, frontend/package.json, frontend/src/app/components/containers/complaints/details/complaint-header.tsx, frontend/src/assets/sass/complaint.scss, webeoc/package.json
https://env-ceds.atlassian.net/browse/CE-1770
---
- [Frontend](https://nr-compliance-enforcement-1164-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1164-frontend.apps.silver.devops.gov.bc.ca/api)
=> feat: CE-1770 Add Lead Agency

backend/package.json, charts/app/Chart.yaml, frontend/package.json, frontend/src/app/components/containers/admin/user-management/edit-user.tsx, frontend/src/app/store/reducers/officer.ts, frontend/src/app/types/person/person.ts, webeoc/package.json
---
- [Frontend](https://nr-compliance-enforcement-1169-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1169-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> feat: CE-1738 allow clearing office,team, park admin page

backend/package.json, charts/app/Chart.yaml, frontend/package.json, frontend/src/app/store/reducers/complaint-outcome-thunks.ts, webeoc/package.json
Fixes # CE-1858
---
- [Frontend](https://nr-compliance-enforcement-1201-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1201-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: Legacy HWCR actions displaying code instead of value

backend/package.json, charts/app/Chart.yaml, frontend/package.json, frontend/src/app/components/common/search-input.tsx, frontend/src/app/components/containers/admin/user-management/edit-user.tsx, frontend/src/app/store/reducers/app.ts, frontend/src/app/store/reducers/complaints.ts, frontend/src/assets/sass/misc.scss, webeoc/package.json
---
- [Frontend](https://nr-compliance-enforcement-1204-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1204-frontend.apps.silver.devops.gov.bc.ca/api)
- [Merge …
=> fix: CE-1864 refinement of search tooltip

backend/package.json, charts/app/Chart.yaml, frontend/package.json, webeoc/package.json
---
- [Frontend](https://nr-compliance-enforcement-1210-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1210-frontend.apps.silver.devops.gov.bc.ca/api)
=> feat: Release/2.5

backend/package.json, backend/src/main.ts, charts/app/Chart.yaml, frontend/package.json, webeoc/package.json
sigh
---
- [Frontend](https://nr-compliance-enforcement-1212-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1212-frontend.apps.silver.devops.gov.bc.ca/api)
=> chore: sigh

migrations/migrations/R__Create-Test-Data.sql, migrations/test-only-migrations/R__Test-Data-Creation.sql
Prevents duplicate/expired user profiles from being re-added to production.
Fixes # (issue) CE-1861
---
- [Frontend](https://nr-compliance-enforcement-1222-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1222-frontend.apps.silver.devops.gov.bc.ca/api)
- [Analysis Workflow](https://github.com/bcgov/nr-compliance-enforcement/actions/workflows/an …
=> chore: Remove duplicate/old users

backend/package.json, charts/app/Chart.yaml, frontend/package.json, frontend/src/app/components/containers/cases/view/case-view.tsx, frontend/src/app/components/containers/cases/view/components/inspection-card.tsx, frontend/src/app/components/containers/cases/view/components/inspection-column.tsx, webeoc/package.json
Add inspections to the column on the case file page.
Fixes # [(issue)](https://env-ceds.atlassian.net/jira/software/c/projects/CE/boards/4?selectedIssue=CE-1814)
---
- [Frontend](https://nr-compliance-enforcement-1228-frontend.apps.silver.devops.gov.bc.ca)
- [Backend](https://nr-compliance-enforcement-1228-frontend.apps.silver.devops.gov.bc.ca/api)
- [Analysis …
=> feat: CE-1814 case inspections

backend/package.json, backend/src/v1/complaint/complaint.service.ts, charts/app/Chart.yaml, frontend/package.json, webeoc/package.json
---
- [Frontend](https://f208ae-dev-8-natsuite-frontend.apps.emerald.devops.gov.bc.ca)
=> fix: CE-1934 COS enforcement still shown when apply filters in Sector view

backend/package.json, charts/app/Chart.yaml, frontend/package.json, frontend/src/app/components/containers/admin/feature-management.tsx, webeoc/package.json
Add a search filter to the admin feature management page.
---
- [Frontend](https://f208ae-dev-4-natsuite-frontend.apps.emerald.devops.gov.bc.ca)
- [Merge Workflow](https://github.com/bcgov/nr-compliance-enforcement/actio …
=> chore: Feature management search

backend/package.json, backend/src/v1/officer/officer.service.ts, backend/src/v1/person/person.controller.ts, backend/src/v1/person/person.service.spec.ts, backend/src/v1/person/person.service.ts, charts/app/Chart.yaml, docker-compose.yml, frontend/package.json, frontend/src/app/App.tsx, frontend/src/app/components/containers/layout/header.tsx, frontend/src/app/store/reducers/app.ts, webeoc/package.json
---
- [Frontend](https://f208ae-dev-7-natsuite-frontend.apps.emerald.devops.gov.bc.ca)
=> fix: CE-1800 

backend/package.json, charts/app/Chart.yaml, frontend/package.json, frontend/src/app/components/containers/complaints/complaint-filter.tsx, webeoc/package.json
---
- [Frontend](https://f208ae-dev-8-natsuite-frontend.apps.emerald.devops.gov.bc.ca)
=> feat: remove agency specific filters
